### ISSUE TITLE
Please explain how to use wordpress:cli

### ISSUE THREAD

**Issue by mans0954** [docker-library/docs#1023]
Please could some documentation regarding use of the wordpress:cli image be added? Thanks.

**Comment by tianon** [comment]
The PR which added this has the suggested usage: https://github.com/docker-library/wordpress/pull/198

The basic gist is that to interact with a WordPress install in the way that wp-cli does, one needs access to the on-disk files of the WordPress install, and access to the database (and the easiest way to accomplish that such that `wp-config.php` does not require changes is to simply join the networking context of the existing and presumably working WordPress container).

We definitely need a blurb about this, but I'd like to keep it as simple as possible (and leave extrapolation into more advanced use cases as an exercise for the reader).
