### ISSUE TITLE
Missing WORDPRESS_DEBUG environment variable reference

### ISSUE THREAD

**Issue by rossjcooper** [docker-library/docs#1042]
The documentation misses out the `WORDPRESS_DEBUG` environment variable which I found to be quite important when using it to develop locally when `WP_DEBUG` is required to be `true`.

The only reference to it I have found is in a PR from a couple of years ago.

**Comment by tianon** [comment]
For reference, the PR in question is https://github.com/docker-library/wordpress/pull/108. :+1:

(... and yes, it's an oversight that this isn't documented, and we should include a short blurb about it :+1: :heart:)
