### ISSUE TITLE
Missing license.md files

### ISSUE THREAD

**Issue by tianon** [docker-library/docs#1046]
Several images here are missing `license.md`, and we'd like to add that to Travis for verifying that everything has it.  The full list of images currently missing `license.md` is as follows:

- [x] alpine: #1089
- [x] amazonlinux: #1061
- [x] cassandra: #1048
- [x] centos: #1090
- [x] cirros: #1091
- [x] clearlinux: #1047
- [x] crux: #1048
- [x] debian: #1048
- [x] fedora: #1049
- [x] ghost: #1048
- [x] hello-seattle: #1048
- [x] hello-world: #1048
- [x] hola-mundo: #1048
- [x] jenkins: #1048
- [x] mageia: #1054
- [x] mariadb: #1048
- [x] mongo-express: #1048
- [x] mysql: #1048
- [x] neo4j: #1086
- [x] neurodebian: #1048
- [x] nginx: #1057
- [x] opensuse: #1051
- [x] orientdb: #1085
- [x] percona: #1048
- [x] postgres: #1048
- [x] registry: #1092
- [x] scratch: literally the empty image; no reason for `license.md`
- [x] ubuntu: #1048
- [x] wordpress: #1048

**Comment by tianon** [comment]
@ncopa do you know what we ought to list for the license of Alpine Linux itself?

@yarikoptic should this blurb be any different for `neurodebian` than it might be for Debian itself?

cc @ilianaw @praveen-pk @Eric-Warehime (`amazonlinux`)
cc @jperrin (`centos`)
cc @ewindisch (`cirros`)
cc @bryteise (`clearlinux`)
cc @maxamillion @puiterwijk (`fedora`)
cc @juanluisbaptiste (`mageia`)
cc @knickers (`mongo-express`)
cc @benbc @spacecowboy @srbaker @praveenag (`neo4j`)
cc @thresheek (`nginx`)
cc @flavio @cyphar @jordimassaguerpla @davidcassany (`opensuse`)
cc @robfrank (`orientdb`)
cc @stevvooe @dmp42 @RichardScothern @aaronlehmann @dmcgowan (`registry`)

If any of you don't have the time for a PR for this, feel free to simply provide the relevant one-liner I ought to put into `license.md` and I'll be happy to make the update on your behalf. :+1:

Most of the existing files use something similar to the following, but any free-form description of the image license information will do:

```markdown
View [license information](URL-TO-UPSTREAM-LICENSE-INFO) for the software contained in this image.
```

**Comment by tianon** [comment]
@prologic I know it's deprecated, but any idea what would be an appropriate blurb to note for `license.md` on `crux`? :pray:

**Comment by yarikoptic** [comment]
@tianon thanks for asking.  I guess pointing to DFSG should be sufficient for the neurodebian images as well, besides may be (since we now provide also -nonfree flavors) adding a note that "-nonfree flavors of the images enable access to materials which are not fully DFSG-compliant, and might have restrictions (e.g. non-commercial) and/or lack original sources."

**Comment by maxamillion** [comment]
@tianon Fedora fixed with #1049

**Comment by prologic** [comment]
Thanks Fredrik!


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by ilianaw** [comment]
Speaking for `amazonlinux`: I'm opening an issue internally to get a proper answer on what to put in a license.md. Feel free to ping me on IRC for information on how that's going.

**Comment by juanluisbaptiste** [comment]
Here is the link for mageia: https://www.mageia.org/en/about/license/

**Comment by thresheek** [comment]
@tianon for nginx it'll be http://nginx.org/LICENSE - although we're based on top of stretch/alpine images so I gather a myriad of licenses will need to be followed as well.

**Comment by tianon** [comment]
@thresheek that's a good point -- we should probably add some boilerplate about that :+1:

**Comment by tianon** [comment]
We're sooo close to finishing this!  Just a friendly re-ping to a few maintainers: (and a re-offer to perform the necessary PR/update if given a link to upstream license information or a blurb of text that it should contain)

cc @ncopa (`alpine`)
cc @jperrin (`centos`)
cc @ewindisch (`cirros`)
cc @benbc @spacecowboy @srbaker @praveenag (`neo4j`)
cc @robfrank (`orientdb`)
cc @stevvooe @dmp42 @RichardScothern @aaronlehmann @dmcgowan (`registry`)

**Comment by tianon** [comment]
Here's the best info I can find for each -- it'd be great if one of the relevant maintainers could at least confirm for any of these images (so I can make the update PR):

- `alpine`: https://github.com/gliderlabs/docker-alpine/blob/master/LICENSE, but also https://forum.alpinelinux.org/forum/general-discussion/licensing-model and/or https://forum.alpinelinux.org/forum/general-discussion/alpine-linux-license (which are both frankly a little depressing) ?

- `centos`: https://www.centos.org/legal/ ?

- `cirros`: https://launchpad.net/cirros
  > (The code for building CirrOS is available under GPLv2. The binary images that will be distributed contain many different licenses all of which are opensource.)

- `neo4j`: https://neo4j.com/licensing/ ?

- `orientdb`: https://github.com/orientechnologies/orientdb/blob/develop/license.txt ?

- `registry`: https://github.com/docker/distribution/blob/master/LICENSE ?

**Comment by tianon** [comment]
@ncopa maybe for Alpine, linking to https://pkgs.alpinelinux.org/packages will be enough?  (especially with the extra boilerplate we added in https://github.com/docker-library/docs/pull/1058)

**Comment by tianon** [comment]
@robfrank oh, you're off the hook! (file exists, but with a typo'd name: `orientdb/licence.md -> orientdb/license.md`)

**Comment by robfrank** [comment]
@tianon done on https://github.com/docker-library/docs/pull/1085

**Comment by spacecowboy** [comment]
@tianon see https://github.com/docker-library/docs/pull/1086
