### ISSUE TITLE
The description for "ADVANCED OPTIONS" in the Mediawiki README doesn't make sense

### ISSUE THREAD

**Issue by eherot** [docker-library/docs#1056]
What it says:

-	ADVANCED OPTIONS; Database host: `some-mysql` (for using the `/etc/hosts` entry added by `--link` to access the linked container's MySQL instance)

Is `some-mysql` an environment variable? A command line flag I'm supposed to specify somehow? It's not clear.

And perhaps related: It's not clear exactly how one specifies an external database host name.

**Comment by tianon** [comment]
You didn't specify which image this is regarding, but I'm guessing it's
Drupal?  The "Advanced Options" you're looking for is shown during the
first-time setup wizard, which happens through the browser, and that's
where you'd configure your custom MySQL host name.  Using "some-mysql" is
only appropriate if that's what you used for the name of your link / mysql
container on the same Docker network.
