### ISSUE TITLE
How do you add the icon for an image on Docker Hub?

### ISSUE THREAD

**Issue by jsternberg** [docker-library/docs#1060]
![pasted image at 2017_11_06 05_01 pm](https://user-images.githubusercontent.com/1212129/32473908-73b91488-c32f-11e7-8115-5cbc5271b805.png)

In the above image, you can see chronograf uses some default image, but the other images use more appropriate logos. I am looking in this repository to see if there is an extra file we need to upload to get that icon, but the only one I see is the image for the docs page itself.

How can I customize the icon seen in that picture for chronograf and the other InfluxData images?

**Comment by tianon** [comment]
Unfortunately, we don't have any access/control for that. :disappointed:

@programmerq are you still an appropriate contact to proxy an internal issue to the Hub team for updating these?

- `chronograf`: https://github.com/docker-library/docs/blob/5fa6f9ace41aa0ded6bdf4df56f746edf43c5843/chronograf/logo.png
- `telegraf`: https://github.com/docker-library/docs/blob/5fa6f9ace41aa0ded6bdf4df56f746edf43c5843/telegraf/logo.png
- `influxdb`: https://github.com/docker-library/docs/blob/5fa6f9ace41aa0ded6bdf4df56f746edf43c5843/influxdb/logo.png
- `kapacitor`: https://github.com/docker-library/docs/blob/5fa6f9ace41aa0ded6bdf4df56f746edf43c5843/kapacitor/logo.png

(they're all the same "influxdata" logo)

**Comment by tianon** [comment]
Closing, since there's nothing we can do from the perspective of this repo (or anywhere else in our repos, for that matter).  Hopefully it's updated soon! :heart:

**Comment by tianon** [comment]
This is now fixed! :+1: :tada:
