### ISSUE TITLE
Broken configuration template link

### ISSUE THREAD

**Issue by alinepegas** [docker-library/docs#1084]
The configuration template link mentioned in docs/odoo/README.md is broken.
https://github.com/odoo/docker/blob/master/8.0/openerp-server.conf

**Comment by tianon** [comment]
cc @d-fence (the `odoo` image maintainer)

**Comment by tianon** [comment]
Closing since this isn't something we (the official-images maintainers) are going to resolve -- @d-fence if there's something that needs to be done here, please open a PR? :pray: :heart:

**Comment by d-fence** [comment]
Sorry, 8.0 isn't supported any more.
