### ISSUE TITLE
Admin username and password

### ISSUE THREAD

**Issue by umardraz** [docker-library/docs#1117]
Hi

Can we create admin usernamd and password while launching docker container?

**Comment by yosifkit** [comment]
To which image are you referring? This repo is for the Docker Hub docs of all Official Images. If the docs do not mention a username and password environment variable then it is probably not part of the image.

You may want to look under the "Where to get help" bullet point of the "Quick reference" section of the docs for the image you are using (like [this](https://github.com/docker-library/docs/tree/cb4cf3d2a762240ec22b9f60d1cbdc8bf0ae77dc/adminer#quick-reference) for adminer).
