### ISSUE TITLE
remove the deprecated and removed 8083 Administrator interface port

### ISSUE THREAD

**Issue by rdxmb** [docker-library/docs#1136]
> ' 8083 Administrator interface port, if it is enabled ' 

should be removed in the docs, for

> 'The administrator interface is deprecated as of 1.1.0 and will be removed in 1.3.0.'

**Comment by yosifkit** [comment]
Oh, you mean [here](https://github.com/docker-library/docs/blob/e8dfc2f2217fac8ac72428afcbb21cf674dd6b87/influxdb/content.md#exposed-ports) for influxdb?  That would be up to the maintainers of the image.

CC @jsternberg

**Comment by rdxmb** [comment]
yes. Is there another repository for that?

**Comment by yosifkit** [comment]
This is the correct repo for that doc, but I was at first unsure which image you were talking about since there are docs for 136 Docker image repos.  It is up to the maintainer of the image on changes to their docs (which is why I pinged them).

**Comment by jsternberg** [comment]
I've seen this message. I'm going to take a look, but have been unable to.

Just replying to confirm that I've seen this.

**Comment by tianon** [comment]
Closing old issue.  If this is still a problem, a PR would be excellent. 👍

**Comment by rdxmb** [comment]
confused. There **is** a PR linked above, open for about one year.

**Comment by tianon** [comment]
Doh, thanks -- @jsternberg, mind taking a look at #1141?

**Comment by jsternberg** [comment]
Sure.

**Comment by rdxmb** [comment]
wait a second, there is something missing cc @jsternberg

**Comment by rdxmb** [comment]
just created a new PR, so please look at them separately
@jsternberg
