### ISSUE TITLE
Why is there no minor version alias to hotfix versions?

### ISSUE THREAD

**Issue by ohartl** [docker-library/docs#1139]
`6.7` should be he latest `6.7.*` (currently `6.7.1`), but instead it is used as the `6.7.0`.

Hence I need to manually update and commit my docker-compose files, again and again for hotfixes..

**Comment by tianon** [comment]
This is definitely filed in the wrong place -- I'd recommend looking under "where to file issues" on the Docker Hub description for the image you're talking about.

This repository is the general repository for ~137 official images, and as such most of the maintainers do not follow it (and thus won't see your tagging recommendation).  Thanks!
