### ISSUE TITLE
systemd base image systemd service removal too harsh for non-root sshd users pam_nologin

### ISSUE THREAD

**Issue by ewak** [docker-library/docs#1173]
The recommended removal of systemd services is too aggressive, the systemd-user-sessions.service oneshot is not run which results in /var/run/nologin not being removed.  This prevents non-root users from logging via ssh(If thats what you also setup) due to pam_nologin.

If you look at the logs with journalctl -f you see errors like the following when a non-root user attempts and fails to ssh in.
sshd[65]: fatal: Access denied for user "non-root-username" by PAM account configuration  [preauth]

Here is what worked for me
```
FROM centos:7
ENV container docker
RUN yum -y swap -- remove fakesystemd -- install systemd systemd-libs
RUN yum -y update; yum clean all; \
    (cd /lib/systemd/system/sysinit.target.wants/; \
        for i in *; do \
            [ $i == systemd-tmpfiles-setup.service ] || \
            rm -f $i; \
        done); \
    (cd /lib/systemd/system/multi-user.target.wants/; \
        for i in *; do \
            [ $i == systemd-user-sessions.service ] || \
            rm -f $i; \
        done); \
    rm -f /etc/systemd/system/*.wants/*; \
    rm -f /lib/systemd/system/local-fs.target.wants/*; \
    rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
    rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
    rm -f /lib/systemd/system/basic.target.wants/*; \
    rm -f /lib/systemd/system/anaconda.target.wants/*;
```

**Comment by tianon** [comment]
This is the repo for the docs, which the individual image maintainers don't
typically follow; I'd recommend bringing this up as an issue on the image
bug tracker instead.

**Comment by yosifkit** [comment]
> -	**Where to file issues**:  
>	[https://bugs.centos.org](https://bugs.centos.org) or [GitHub](https://github.com/CentOS/sig-cloud-instance-images/issues)
>
> \- from [docs](https://github.com/docker-library/docs/tree/e68be889c9a97c0bed0fd442da22676640f1ade3/centos#quick-reference)
