### ISSUE TITLE
How to automate this repo?

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/docs#1186]
For matomo, we keep the README up to date, and it is tedious for each change to come here, and make a manual PR.

Do you have any automation for that part too?

Thanks!

Related to https://github.com/matomo-org/docker/pull/88

**Comment by tianon** [comment]
Unfortunately not, especially as the Matomo `README.md` file does not use our templating variables, so won't be drop-in compatible.

For the images we maintain, we instead opt to keep their `README.md` files extremely minimal and point to this repo / Docker Hub as the source of truth for the image description.

See https://github.com/docker-library/docs/blob/0ae2dfcd0df23423f769d7bd9a27675df0ed190d/generate-repo-stub-readme.sh for the script we use to generate those `README` stub files for the individual repositories.
