### ISSUE TITLE
[Question] Why is not generated a new docker jenkins image based on  2.107.2 release?

### ISSUE THREAD

**Issue by alinpa** [docker-library/docs#1213]
Hello, 

Please let me know why is not generated a new image based on  2.107.2 release and we have the 2.60.3 version?

**Comment by tianon** [comment]
See https://hub.docker.com/_/jenkins/, especially the deprecation notice at the top:

> # **DEPRECATION NOTICE**
> 
> This image has been deprecated in favor of the [`jenkins/jenkins:lts`](https://hub.docker.com/r/jenkins/jenkins) image provided and maintained by [Jenkins Community](https://jenkins.io/) as part of project's release process. The images found here will receive no further updates after LTS 2.60.x. Please adjust your usage accordingly.
