### ISSUE TITLE
--user will not work as documented.

### ISSUE THREAD

**Issue by zipi** [docker-library/docs#1218]
Changes in Docker have broken this capability. I have not found any combination of bind mounts and --user that will run without throwing an error.  It would be great if someone could tell me to use the official registry image with an easy way to keep all data files correctly owned by each developer. I think adding a build property to the postgres service in the compose file should work, but you guys will want to update the README.

**Comment by SushilShrestha** [comment]
experiencing similar problem with --user on `psql` command
