### ISSUE TITLE
Some of the listed tags are not available in docker hub

### ISSUE THREAD

**Issue by panmanphil** [docker-library/docs#1281]
Just last week I had been able to pull some the mongo:4.0-windowservercore-1803 images but no longer. The 3.6 windowsservercore-1709 do still work:

```
docker pull --platform windows mongo:3.6-windowsservercore-1709
3.6-windowsservercore-1709: Pulling from library/mongo
5847a47b8593: Already exists
a01c2a39b5bd: Pull complete
d0dc9d8f5ea2: Pull complete
5c3840e69e78: Pull complete
aaa72df16922: Pull complete
23e1d36b3c46: Pull complete
23a2dcd8c95f: Pull complete
e0176aa7ea35: Pull complete
13ceb5164df3: Pull complete
3872604e12d9: Pull complete
Digest: sha256:fe2301a8d71976612d24c096e4dd679191c3f3035c79ad567ecfe1d297a1c750
Status: Downloaded newer image for mongo:3.6-windowsservercore-1709

docker pull --platform windows mongo:4.0-windowsservercore-1803
4.0-windowsservercore-1803: Pulling from library/mongo
no matching manifest for windows/amd64 in the manifest list entries
```
None of the variations for the 1803 images worked for me.

**Comment by yosifkit** [comment]
Sounds like https://github.com/docker-library/official-images/issues/3835.

The update was merged in https://github.com/docker-library/official-images/pull/4713. Builds that are not Linux/amd64 are only triggered once a day to limit 3835's impact. So the Windows build was done here: https://doi-janky.infosiftr.net/job/multiarch/job/windows-amd64/job/mongo/5 to push to the `winamd64` namespace on the Docker Hub. Then later the manifest list tags were updated via https://doi-janky.infosiftr.net/job/put-shared/job/light/ to update the empty namespace (aka `library/`).
