### ISSUE TITLE
README <pre> blocks lack CSS margin

### ISSUE THREAD

**Issue by nslater** [docker-library/docs#1321]
example:

https://hub.docker.com/_/crate/

search for the following code:

```
docker run -p 4200:4200 crate
```

notice that there is a missing margin below the `<pre>` block, meaning that it is displayed as if the only thing separating it from the next paragraph is a single line break

this is inconsistent with the rest of the design, which separates paragraphs and other block-level elements with more space

**Comment by yosifkit** [comment]
Unfortunately the styling on Docker Hub is not something we control. We just provide the markdown from this repo.  You can try filing an issue through https://github.com/docker/hub-feedback.

**Comment by tianon** [comment]
See also specifically https://github.com/docker/hub-feedback/issues/179, https://github.com/docker/hub-feedback/issues/323, https://github.com/docker/hub-feedback/issues/124.

**Comment by nslater** [comment]
thank you!
