### ISSUE TITLE
OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

### ISSUE THREAD

**Issue by qiulang** [docker-library/docs#1437]
Use the code from here https://github.com/docker-library/docs/tree/master/nginx#using-environment-variables-in-nginx-configuration

`command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"` 

Got the error, 

ERROR: for xxx_1  Cannot start service xxx: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

ERROR: for xxx  Cannot start service xxx: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.

Change /bin/bash to /bin/sh then works.

But why ?

**Comment by tianon** [comment]
You must've switched `image:` to the Alpine variant, which doesn't include
Bash.

**Comment by qiulang** [comment]
But the image has bash!

**Comment by tianon** [comment]
Can you please share your full compose file so we can try to reproduce?

**Comment by qiulang** [comment]
Sorry my mistake, it is indeed like you said,  FROM nginx:stable-alpine as production-stage.
So no  bash. My bad
