### ISSUE TITLE
The description of the Geonetwork image on docker hub is incomplete

### ISSUE THREAD

**Issue by doublebyte1** [docker-library/docs#1480]
The [description](https://hub.docker.com/_/geonetwork) of the image on docker hub does not match the [README.md](https://github.com/docker-library/docs/blob/master/geonetwork/README.md). It misses all the sections from [this](https://github.com/docker-library/docs/blob/master/geonetwork/README.md#-via-docker-stack-deploy-or-docker-compose) point.

**Comment by yosifkit** [comment]
I just checked the description that is uploaded there and it is all correct. It seems to be a new parsing bug on Docker Hub.  I think it is struggling on html-like "tags" within a code block:
````markdown
host into the container. - `-v <host path>:<data directory>`. For instance this, will mount the host directory `/host/geonetwork-docker` into `/var/lib/geonetwork_data` on the container:
````

You probably need to file an issue with docker. I think https://github.com/docker/hub-feedback/issues is still watched, or you could try support@docker.com.

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker/hub-feedback/issues/1849 :disappointed:
