### ISSUE TITLE
Only centos:7 available for ARM64

### ISSUE THREAD

**Issue by albertvaka** [docker-library/docs#1522]
Only the latest version of the CentOS 7 image (`centos:7` and `centos:latest`) is available for ARM. No minor version images (eg: `centos:7.6.1810`) are provided, like they are on x86. Is this intended?

**Comment by wglambert** [comment]
We're not the maintainers of that image https://hub.docker.com/_/centos/

- Maintained by:
[The CentOS Project](https://github.com/CentOS/sig-cloud-instance-images)

Searching through their issues there's nothing for "arm"

**Comment by albertvaka** [comment]
Will open an issue there, thanks!

**Comment by albertvaka** [comment]
Linking here for reference: https://github.com/CentOS/sig-cloud-instance-images/issues/145
