### ISSUE TITLE
Error response from daemon: error processing tar file: docker-tar: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

### ISSUE THREAD

**Issue by chosen1cwp** [docker-library/docs#1541]
when 

docker cp nginx:/etc/nginx/conf.d/default.conf /root/www/default.conf

i got follow error :

Error response from daemon: error processing tar file: docker-tar: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
: exit status 127

**Comment by suvatojo** [comment]
How did you resolve this?
