### ISSUE TITLE
postgres: Initialization Scripts section is missing content on hub

### ISSUE THREAD

**Issue by ms1111** [docker-library/docs#1558]
On Docker Hub: https://hub.docker.com/_/postgres?tab=description&page=2

I think something doesn't like the `<<-EOSQL` in the Initialization Scripts section, and skips over the last part of the Initialization Scripts section and the first part of the Database Configuration section.

![image](https://user-images.githubusercontent.com/17057295/63194422-fce64c00-c03d-11e9-821d-c517809528a9.png)

Compare with the original content from https://github.com/docker-library/docs/tree/master/postgres:

![image](https://user-images.githubusercontent.com/17057295/63194461-17b8c080-c03e-11e9-9f42-c3fd283a86ee.png)

**Comment by yosifkit** [comment]
Already filed upstream: https://github.com/docker/hub-feedback/issues/1849.  There is not much else we can do from here.
