### ISSUE TITLE
please add libfontconfig1 to adoptopenjdk images

### ISSUE THREAD

**Issue by bzaicsek-cxn** [docker-library/docs#1565]
adoptopenjdk images miss a dependency of java which is required for its correct work

I have an example here: https://github.com/bzaicsek-cxn/image-generation-bug

libfontconfig1 library adds an extra 6 MB to an image but built in Java classes (like: FontManager) uses it as a native implementation. This makes adoptopenjdk images to be unable to generate images with text by default

this lib is a dependency of the openjdk deb installers on other systems

**Comment by tianon** [comment]
From https://hub.docker.com/_/adoptopenjdk:

> -	**Where to file issues**:  
> 	[GitHub](https://github.com/AdoptOpenJDK/openjdk-docker/issues); The [adoptopenjdk support](https://adoptopenjdk.net/support.html) page has more information on quality, roadmap and support levels for AdoptOpenJDK builds;

This repository only holds the image documentation.

**Comment by bzaicsek-cxn** [comment]
Sorry and thank you!
