### ISSUE TITLE
IRSSI docs need update for Mac users

### ISSUE THREAD

**Issue by moxiegirl** [docker-library/docs#157]
While running this image I ran into an issue on my Mac with the `localtime` mount.  Searched web to find this is no longer needed on Mac.

Talking to @jfrazelle confirmed that the command line is Linux specific. The docs should be updated for Mac use --- I'm planning on doing that shortly.

**Comment by tianon** [comment]
> I ran into an issue on my Mac with the `localtime` mount.

Can you expound on what the issue is?  The mount won't be doing on Mac OS what it does on Linux, but it should be reasonably harmless (since it'll just be bind-mounting in boot2docker's timezone instead, which will get you UTC, just like the container already defaults to).

**Comment by jfrazelle** [comment]
I think because b2d uses remote volumes er whatever now it is trying to
find /etc/localtime on the mac...

On Mon, Feb 9, 2015 at 10:49 AM, Tianon Gravi <notifications@github.com>
wrote:

> I ran into an issue on my Mac with the localtime mount.
>
> Can you expound on what the issue is? The mount won't be doing on Mac OS
> what it does on Linux, but it should be reasonably harmless (since it'll
> just be bind-mounting in boot2docker's timezone instead, which will get you
> UTC, just like the container already defaults to).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker-library/docs/issues/157#issuecomment-73565711>.
>



-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by moxiegirl** [comment]
@tianon it actually threw an error...this:

```
$ docker run -it --name meepir -e TERM -u $(id -u):$(id -g) -v $HOME/.irssi:/home/user/.irssi:ro  -v /etc/localtime:/etc/localtime:ro irssi
setup mount namespace mounting /etc/localtime into /mnt/sda1/var/lib/docker/aufs/mnt/a2477ddcdeb62d29c2981bbdd7296d5d44bd9874da62205a520aaa50f2966ed9/etc/localtime not a directoryFATA[0000] Error response from daemon: Cannot start container a2477ddcdeb62d29c2981bbdd7296d5d44bd9874da62205a520aaa50f2966ed9: setup mount namespace mounting /etc/localtime into /mnt/sda1/var/lib/docker/aufs/mnt/a2477ddcdeb62d29c2981bbdd7296d5d44bd9874da62205a520aaa50f2966ed9/etc/localtime not a directory 
```
I'm running yosemite.  I googled this error and checked with @jfrazelle before making this change.  But I didn't test further on other Mac ver.

**Comment by tianon** [comment]
@jfrazelle the Mac mount only includes `/Users`, so it shouldn't affect this

However, it does look like boot2docker doesn't use `/etc/localtime`, which is the reason this is failing (super bizarre), so I guess the docs change makes sense. :+1:
```console
docker@boot2docker:~$ cat /etc/localtime
cat: can't open '/etc/localtime': No such file or directory
```

**Comment by moxiegirl** [comment]
@tianon This tidbit on b2d worth mentioning in the docs?

**Comment by tianon** [comment]
IMO, yes! :+1:

**Comment by moxiegirl** [comment]
done
