### ISSUE TITLE
503 status erros, while pulling an image

### ISSUE THREAD

**Issue by JhonydePaula22** [docker-library/docs#1589]
Hey,

I am trying to run the following command:

`docker pull openjdk:8`

But I am getting the following response:

`Error response from daemon: received unexpected HTTP status: 503 Service Unavailable`

Could you help me on that?

**Comment by wglambert** [comment]
Dockerhub is having some issues docker/hub-feedback#1897

Going to close since the hub-feedback repo is the appropriate place for this

**Comment by JhonydePaula22** [comment]
Thanks!
