### ISSUE TITLE
Plone logo not up-to-date

### ISSUE THREAD

**Issue by avoinea** [docker-library/docs#1592]
The Plone logo at https://hub.docker.com/_/plone is not the one updated within https://github.com/docker-library/docs/pull/1052.

Could you please invalidate cache, or check why it is still rendering the old PNG one instead of SVG.

**Comment by yosifkit** [comment]
The logo at the top is still not updated by us.  We have been given an API to do so, but have been unable to successfully use it yet.  The logo at the top will be automatic as soon as we get it working.

The current plan will be to autogenerate a 120x120 image from the `logo.[svg,png]` file and push that with an override by providing a `logo-120.png` in the appropriate folder.

**Comment by tianon** [comment]
This is now updated! :+1: :tada:
