### ISSUE TITLE
Want to specify multi databases/schemas with MYSQL_DATABASE

### ISSUE THREAD

**Issue by hatzhang** [docker-library/docs#1613]
like the following:
MYSQL_DATABASE=db1;db2;db3

there are some workarounds:
https://gist.github.com/MKagesawa/a03892b8c44c015cd991c2c5311f1768

**Comment by wglambert** [comment]
You can make a `.sql` file that will create databases and mount it to `/docker-entrypoint-initdb.d/`
https://github.com/docker-library/docs/tree/master/mysql#initializing-a-fresh-instance

**Comment by yosifkit** [comment]
Correct, we only support one database in the `MYSQL_DATABASE` variable and any further SQL needed should be done via `/docker-entrypoint-initdb.d/`.

See also https://github.com/docker-library/postgres/pull/240#issuecomment-314228559
