### ISSUE TITLE
[openjdk] Is there a 8u232-alpine image?

### ISSUE THREAD

**Issue by umnagendra** [docker-library/docs#1618]
I am using `openjdk:8u212-alpine3.9` so far, and I wanted to update to something like `8u232-alpine3.10`

I see 8u232 based images for `windowsservercore`, but not alpine.

**Comment by wglambert** [comment]
We have a reference list for the OpenJDK variants https://github.com/docker-library/openjdk/issues/272

>Alpine is not officially supported by the OpenJDK project https://github.com/docker-library/openjdk/pull/322, https://github.com/docker-library/openjdk/issues/211#issuecomment-426708580, https://github.com/docker-library/openjdk/pull/235#issuecomment-424599754
