### ISSUE TITLE
Rust compiled binary example is incorrect

### ISSUE THREAD

**Issue by elpiel** [docker-library/docs#1634]
The issues with the example below is that the binary installation directory is actually `$CARGO_HOME/bin`, in the example it copies the Source code directory (`COPY --from=builder /usr/src/myapp /usr/local/bin/myapp`) which is not executable and thus this won't work.

The example:
```
FROM rust:1.39 as builder
WORKDIR /usr/src/myapp
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y libssl
COPY --from=builder /usr/src/myapp /usr/local/bin/myapp
CMD ["myapp"]
```

**Comment by tianon** [comment]
Good catch!

cc @mkinney (last to touch this section / author of this bit), @sfackler (`rust` image maintainer)
