### ISSUE TITLE
Provide images for 11.0.6 and 8u242 variants

### ISSUE THREAD

**Issue by aanno2** [docker-library/docs#1644]
11.0.6 and 8u242 hit the road on https://adoptopenjdk.net/ but are - so far - not provided as docker images.

**Comment by wglambert** [comment]
We don't maintain that image
https://hub.docker.com/_/adoptopenjdk
>Maintained by: [AdoptOpenJDK](https://github.com/AdoptOpenJDK/openjdk-docker)

**Comment by wglambert** [comment]
However our [OpenJDK](https://hub.docker.com/_/openjdk) images do have those updates
11.0.6 https://github.com/docker-library/official-images/pull/7282
8u242 https://github.com/docker-library/official-images/pull/7315
