### ISSUE TITLE
wordpress doco claims WORDPRESS_CONFIG_EXTRA is used

### ISSUE THREAD

**Issue by tomkcook** [docker-library/docs#1661]
...but this appears not to be the case.  No variables that I set in `WORDPRESS_CONFIG_EXTRA` are applied to the running wordpress site.

**Comment by tianon** [comment]
Can you please share your container logs? (https://github.com/docker-library/wordpress/pull/142#issuecomment-454226484)

**Comment by tomkcook** [comment]
Never mind.  On trying to pin this down, it does work.
