### ISSUE TITLE
Docs » WordPress » README » Try in PWD No Longer Works

### ISSUE THREAD

**Issue by ilyakam** [docker-library/docs#1734]
The last time I used the "Try in Play With Docker" feature (![Try in PWD](https://github.com/play-with-docker/stacks/raw/cff22438cb4195ace27f9b15784bbb497047afa7/assets/images/button.png)) was about a month ago. Back then, I was able to successfully spin up an instance of WordPress for four hours, make the necessary changes, and demo the features to the interested stakeholders. 

When I tried doing the same thing earlier today, PWD failed with the following error:

```sh
Swarm initialized: current node (b4kaw57994uljxempfzcvcy39) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-0wpa69g65oadk0ugvdoe4iux6h9cl2s3nrvrhx2dbvlnzs23g6-9m61yo5ouhkxu7nzuycuqck27 192.168.0.8:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

sh: docker-compose: Permission denied
```

([Click here to see the screenshot](https://user-images.githubusercontent.com/183227/83978650-d55abb80-a8bd-11ea-91dc-908a0b5df9d4.png))

Here is the code in question:
https://github.com/docker-library/docs/blob/9369d9dacd3ff93c2349bc5890217b36138af94c/wordpress/README.md#L153

I realize that this isn't an issue with the WordPress image per se. Meaning, `docker-compose` throws a "permission denied" error even when I start a new session from scratch. However, the `README` in that image is making it seem like it's supposed to work while that is no longer the case. Since I don't have any visibility as to what's happening behind the scenes with PWD, and all of it falls squarely within the Docker ecosystem, I think that bringing it up in this issue is valid.

To fix, I recommend you first try and get PWD to work as it used to. If that's no longer a possibility due to some business decisions behind closed doors, then please update the `README` to reflect the new changes.

**Comment by tianon** [comment]
Oh, that's no good -- I'm able to reproduce.  I'll send a ping to the folks in charge of Play-With-Docker and see if they know what's up.

(My guess is that there's just a bug in the latest version of something. :see_no_evil: )

**Comment by marcosnils** [comment]
My bad.. I did some changes in PWD during the weekend to bump the environment to the latest engine version and I broke something. Just checked and should be fixed now. 
:coffee: or :beers: on me next time!

**Comment by tianon** [comment]
Confirmed, looks great now; thanks @marcosnils! :heart:

**Comment by ilyakam** [comment]
It looks great on my end, too. Thanks for the quick turnaround, @marcosnils!
