### ISSUE TITLE
The link to the License file on the docs/gcc page appears to be broken.

### ISSUE THREAD

**Issue by graichen** [docker-library/docs#1772]
The link is: 
https://gcc.gnu.org/viewcvs/gcc/trunk/gcc/COPYING3?view=markup
The response is: 
The requested URL /viewcvs/gcc/trunk/gcc/COPYING3 was not found on this server.

**Comment by wglambert** [comment]
https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html might be a good replacement link to use

**Comment by tianon** [comment]
Nice catch! :sweat_smile:

I think https://gcc.gnu.org/onlinedocs/gcc-11.2.0/gcc/Copying.html is probably a better replacement though (that other link is good, but is specific to libstdc++ instead of all of gcc).
