### ISSUE TITLE
Login Loop at apache 20 version

### ISSUE THREAD

**Issue by MartinEnders** [docker-library/docs#1815]
Hi,

when I was setting the redis connection parameters in docker-compose file it resulted in a login-loop.
When I logged in I have been redirected to the login-page immediatly.
Setup: everything in docker, nginx reverse proxy in front of apache-20 version of nextcloud

When I removed the redis-config from the environment it worked fine (s. link below).
I assume that redis is working because it is inserted in the config.php file.

https://help.nextcloud.com/t/login-loop-after-updating-dockerized-nextcloud-to-version-19/88705/3

Now my nextcloud setup works fine.

Best regards
Martin

**Comment by wglambert** [comment]
I think you'd want to file this over at https://github.com/nextcloud/docker/issues

https://hub.docker.com/_/nextcloud
>Maintained by: [Nextcloud](https://github.com/nextcloud/docker)
>Where to file issues: https://github.com/nextcloud/docker/issues

**Comment by MartinEnders** [comment]
Oh sorry.
Thank you for your hint.
