### ISSUE TITLE
При первом входе зависает

### ISSUE THREAD

**Issue by extreen** [docker-library/docs#1819]
При первом входе в браузере после ввода логина и пароля зависает.
Нажимаешь F5 и все норм, входит.
После этого все нормально, выходишь и входишь.
Но стоит сменить комп или хотя бы открыть другой браузер все повторяется.

**Comment by tianon** [comment]
I don't think you've filed this in the right place -- it sounds like you're having trouble with your browser or a specific website/application?

**Comment by extreen** [comment]
проверял на нескольких брайзерах и пк

**Comment by extreen** [comment]
> Не думаю, что вы разместили это в нужном месте - похоже, у вас проблемы с браузером или конкретным веб-сайтом / приложением?

да действительно не в ту вкладку написал
