### ISSUE TITLE
Postgres documentation is truncated at Docker Hub

### ISSUE THREAD

**Issue by he7d3r** [docker-library/docs#1823]
At the moment, the last phrase at https://hub.docker.com/_/postgres is truncated like this:
> The -v /my/own/datadir:/var/lib/postgresql/data part of the command mounts the /my/own/datadir directory from the underlying host system as /var/lib/postgresql/data inside the container, where P

It should be

> The -v /my/own/datadir:/var/lib/postgresql/data part of the command mounts the /my/own/datadir directory from the underlying host system as /var/lib/postgresql/data inside the container, where P**ostgreSQL by default will write its data files.**

and then it should continue with the content of
https://github.com/docker-library/docs/tree/master/postgres#image-variants

**Comment by wglambert** [comment]
There's a 25k character limit on Dockerhub, it used to be 5k https://github.com/docker/hub-feedback/issues/238#issuecomment-398812981

**Comment by yosifkit** [comment]
This is noted at the top of the description:

> Note: the description for this image is longer than the Hub length limit of 25000, so has been trimmed. The full description can be found at https://github.com/docker-library/docs/tree/master/postgres/README.md. See docker/hub-beta-feedback#238 for more information.
