### ISSUE TITLE
Update deprecated Jenkins repo text

### ISSUE THREAD

**Issue by slide** [docker-library/docs#1851]
We would like to update the deprecated Jenkins repo from the official library (https://hub.docker.com/_/jenkins) to make sure people know more about the deprecation. The docs directory has been removed, so we're not sure how to get it updated correctly. We recently worked with @tianon to remove tags from the repo, but would really like to make sure people know that the repo is invalid and that the tags listed are not correct. What is the best way to go about this?

**Comment by tianon** [comment]
Probably best to just get text for a proposed update in a gist or comment here so we can copy it over manually -- the current description's markdown can be gleaned from https://github.com/docker-library/docs/commit/9c857f87a1605b20fe34e8eb3885bb77698f84a5 if that's helpful in coming up with a proposed edit.

**Comment by slide** [comment]
I think something like the following should work:

```
# **DEPRECATION NOTICE**

This image has been deprecated for **over 2 years** in favor of the [`jenkins/jenkins:lts`](https://hub.docker.com/r/jenkins/jenkins) image provided and maintained by the [Jenkins Community](https://jenkins.io/) as part of project's release process. The images found here have not received updates for over 2 years and will not receive any updates in the future.

Remaining tags are here only for historical reasons, none of them are supported and none of them should be used.
```

**Comment by tianon** [comment]
Sounds good -- I've put in the change, but it's going to take some time (probably an hour or so) before it propagates to https://hub.docker.com/_/jenkins (I'm not sure why those updates are delayed, but that's our reality :sweat_smile:).
