### ISSUE TITLE
Still no Nextcloud 20.0.7 in the docker images?

### ISSUE THREAD

**Issue by baderas** [docker-library/docs#1869]
Hi, 

I'm wondering, Nextcloud 20.0.7 was released five days ago and the version in the docker images (all tags that belong to 20*) are still 20.0.6.

But most of the tags were updated 3 days ago.

Could you please update to 20.0.7?

**Comment by tianon** [comment]
This repository is documentation for all official images -- I'd suggest filing an issue at https://github.com/nextcloud/docker where the `nextcloud` image maintainers are more likely to see it.

**Comment by baderas** [comment]
Sorry, I picked the wrong repository. Thank you :-)
