### ISSUE TITLE
The link to the kickstart file used to build this image is dead

### ISSUE THREAD

**Issue by vonbrand** [docker-library/docs#1910]
At least the link that appears in the README

**Comment by wglambert** [comment]
This looks to be filed in the wrong place, we don't make use of any kickstart files

**Comment by tianon** [comment]
It sounds like you're probably referring to the `fedora` image; per https://hub.docker.com/_/fedora, you probably wanted:

> -	**Where to file issues**:  
> 	[Fedora's bugzilla page](https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora) (choose `docker` as component and include details about image problems in the description) or [GitHub](https://github.com/fedora-cloud/docker-brew-fedora/issues)

:sweat_smile: :+1:
