### ISSUE TITLE
Dockerfile for docker:stable

### ISSUE THREAD

**Issue by tretos53** [docker-library/docs#1919]
Hi,

Maybe I'm asking the wrong question and please correct me if I'm wrong.

I use docker:stable but I usually need to install some additional tools (aws cli for example). Doing it every-time it takes time and sometimes breaks, and I wonder if it's possible to get a Dockerfile for docker:stable so I could add those tools and create an image.

**Comment by wglambert** [comment]
The `docker` repo has those https://github.com/docker-library/docker/tree/master/20.10

See also https://hub.docker.com/_/docker/
># Supported tags and respective `Dockerfile` links

-	[`20.10.6`, `20.10`, `20`, `latest`](https://github.com/docker-library/docker/blob/f6a0c427f0354dcf5870c430c72c8f1d6b4e6d5e/20.10/Dockerfile)
-	[`20.10.6-dind`, `20.10-dind`, `20-dind`, `dind`](https://github.com/docker-library/docker/blob/094faa88f437cafef7aeb0cc36e75b59046cc4b9/20.10/dind/Dockerfile)
-	[`20.10.6-dind-rootless`, `20.10-dind-rootless`, `20-dind-rootless`, `dind-rootless`](https://github.com/docker-library/docker/blob/f6a0c427f0354dcf5870c430c72c8f1d6b4e6d5e/20.10/dind-rootless/Dockerfile)
-	[`20.10.6-git`, `20.10-git`, `20-git`, `git`](https://github.com/docker-library/docker/blob/387e351394bfad74bceebf8303c6c8e39c3d4ed4/20.10/git/Dockerfile)
-	[`19.03.15`, `19.03`, `19`](https://github.com/docker-library/docker/blob/835c371c516ebdf67adc0c76bbfb38bf9d3e586c/19.03/Dockerfile)
-	[`19.03.15-dind`, `19.03-dind`, `19-dind`](https://github.com/docker-library/docker/blob/b1d2628005e12e79079c025c3653cba248d6f264/19.03/dind/Dockerfile)
-	[`19.03.15-dind-rootless`, `19.03-dind-rootless`, `19-dind-rootless`](https://github.com/docker-library/docker/blob/835c371c516ebdf67adc0c76bbfb38bf9d3e586c/19.03/dind-rootless/Dockerfile)
-	[`19.03.15-git`, `19.03-git`, `19-git`](https://github.com/docker-library/docker/blob/12d1c2763b54d29137ec448a3e4ad1a9aefae1a0/19.03/git/Dockerfile)

**Comment by tianon** [comment]
You're probably also interested in https://github.com/docker-library/docker/pull/179, which dropped support for the `stable` alias specifically because folks were misinterpreting it (it was the "stable" channel of Docker releases, not a "stable" interface, and now Docker only has a single release channel so it was redundant).
