### ISSUE TITLE
systemd example doesn't work anymore

### ISSUE THREAD

**Issue by dothebart** [docker-library/docs#1936]
over here:

https://github.com/docker-library/docs/tree/master/centos#dockerfile-for-systemd-base-image

describes how to build an image which runs systemd as PID1. 
However, while a container built that way will launch, `/run/` will be missing the sockets for dbus, and 
```
systemctl enable bla
Failed to get D-Bus connection: No such file or directory
```
hence one can't talk to systemd, and not make it launch services etc.

This used to be working until some when last week. This similar Ubuntu container still works: https://github.com/arangodb/release-test-automation/blob/main/containers/docker_deb/Dockerfile 

I've tried https://fedoraproject.org/wiki/How_to_debug_Systemd_problems 
and https://freedesktop.org/wiki/Software/systemd/Debugging/ but I can't get the systemd output - should one be able to see it with `docker logs` if `--log_target=console` or `--systemd.log_target=console`?

**Comment by dothebart** [comment]
hm, when running the container interactive, one has some feedback. Shouldn't these also be seen in `docker logs` ? 
```
docker run -it --ulimit core=-1 --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:rw -v /tmp/tmp:/tmp/  blarg /lib/systemd/systemd --system --unit=multiuser.target 
Failed to mount cgroup at /sys/fs/cgroup/systemd: Operation not permitted
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to CentOS Linux 7 (Core)!

Set hostname to <c5e62f13ab1d>.
Initializing machine ID from random generator.
Cannot determine cgroup we are running in: No such file or directory
Failed to allocate manager object: No such file or directory
[!!!!!!] Failed to allocate manager object, freezing.
```

So at least now I have some feedback from systemd what to continue googling.

**Comment by dothebart** [comment]
Quoting https://systemd.io/CONTAINER_INTERFACE/ - 
```
Note that it is our intention to make systemd systems work flawlessly and out-of-the-box in containers. In fact we are interested to ensure that the same OS image can be booted on a bare system, in a VM and in a container, and behave correctly each time. If you notice that some component in systemd does not work in a container as it should, even though the container manager implements everything documented above, please contact us.
```
and reading the rest of the page it seems that there still seems to be some manual configuration to work with. 
Instead of mounting `/sys` readonly, the udev services are removed, which seems to be all against systemd's policy.

**Comment by iMacTia** [comment]
@dothebart did you manage to solve this by any chance?

**Comment by dothebart** [comment]
It seems that it fails with newer kernels. Upstream systemd says: docker does it all wrong:
https://github.com/systemd/systemd/issues/19504
It seems to work with other containerizers.

**Comment by iMacTia** [comment]
For future readers, I was trying to run Ansible playbooks with the service module against the `amazonlinux` Docker image.
The solution for me was to use [this systemctl replacement](https://github.com/gdraheim/docker-systemctl-replacement/blob/master/SERVICE-MANAGER.md) and explicitly tell the service module to use `systemd` as the [auto-detection was failing](https://github.com/ansible/ansible-modules-core/issues/4024#issuecomment-234743022).

**Comment by tianon** [comment]
@bstinsonmhk ￼:pray: is this example still relevant?  Should it be updated or removed?

**Comment by dothebart** [comment]
From my POV yes! Our @arangodb CI leans on this for nightly package testing.
