### ISSUE TITLE
mysql bug

### ISSUE THREAD

**Issue by ChenchaoZhao** [docker-library/docs#1987]
in the docker compose file
MYSQL_HOST should be left empty
otherwise the database will not init

**Comment by wglambert** [comment]
Duplicate of https://github.com/docker-library/mysql/issues/184

https://github.com/docker-library/docs/tree/master/mysql#environment-variables
>See also https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html for documentation of environment variables which MySQL itself respects (especially variables like `MYSQL_HOST`, which is known to cause issues when used with this image).
