### ISSUE TITLE
Shared class cache directory isn't correct

### ISSUE THREAD

**Issue by brenthdaniel** [docker-library/docs#2010]
In the JRE Class data sharing section of the README, there are a couple of references to:
`/opt/ibm/wlp/output/.classCache`

This is not correct -- the actual value is `$WLP_OUTPUT_DIR/.classCache`, which will end up being something like:
`/opt/ibm/wlp/output/defaultServer/.classCache`  (so, essentially, it's missing the server name, which is `defaultServer` by default.)

**Comment by tianon** [comment]
I'm gonna assume this must be about `websphere-liberty`?

cc @crpotter @wraschke @arthurdm

**Comment by tianon** [comment]
@crpotter @wraschke @arthurdm is this still relevant?
