### ISSUE TITLE
Unable to update Aerospike Official image Documentation

### ISSUE THREAD

**Issue by volmarl** [docker-library/docs#2026]
@yosifkit , @tianon , We are currently unable to update the Aerospike official image documentation using [this repo](https://github.com/docker-library/docs/tree/master/aerospike). The hub content for the official image used to be auto-generated by updating info on the github repo:

https://github.com/docker-library/docs/tree/master/aerospike

The hub page seems to have been reverted to Publisher:

https://hub.docker.com/_/aerospike

Could you either revert to the old way of updating the official image documentations through github or give publisher access to all the maintainers with instructions.

Thanks.

**Comment by yosifkit** [comment]
Yeah the description should definitely be updated by this repo. I've contacted Docker Inc. to see if they can just drop the Store/Publisher interface so that things will work again.

**Comment by jonnystoten** [comment]
Hi @volmarl, we've updated the hub page to display the official image so you should be able to update the documentation with this repo again.

**Comment by tianon** [comment]
Nice, thanks @jonnystoten! :metal:
