### ISSUE TITLE
I mount the /var/www/html directory to the host directory，it fails to start.

### ISSUE THREAD

**Issue by yangzong18** [docker-library/docs#2034]
Hello, I created the nextcloud container in docker. If I mount the /var/www/html directory to the host directory, it fails to start.
Remove this mount, you can run successfully, I don't know why?

**Comment by wglambert** [comment]
Maybe there's hidden files/folders in the directory you're mounting, so Nextcloud won't overwrite anything and fails

This isn't the right place to file an issue about it though https://hub.docker.com/_/nextcloud
>Where to file issues: https://github.com/nextcloud/docker/issues
