### ISSUE TITLE
custom_addons

### ISSUE THREAD

**Issue by luna9722** [docker-library/docs#2072]
Hello everybody,
I am totally new to odoo and I am trying to run a docker container using docker-compose like it is well explained here: https://hub.docker.com/_/odoo?tab=description while specifying the custom-addons directory but I found that I can find these modules only by activating the developer mode and updating the apps so I can install, is there not a way to find directly and installing them without doing this ?
Thank you

**Comment by wglambert** [comment]
We're not the maintainers of that image

>Maintained by: [Odoo](https://github.com/odoo/docker)
>Where to file issues: https://github.com/odoo/docker/issues

You might find a similar issue already made over on their repo
