### ISSUE TITLE
eclipse-temurin:17-jdk-* VS eclipse-temurin:17-jre-*

### ISSUE THREAD

**Issue by chibenwa** [docker-library/docs#2086]
Hello there.

I see `eclipse-temurin:17-jdk-*` on docker hub and no `eclipse-temurin:17-jre-*`.

Is there any reason? Any plan to support those in the future?

**Comment by wglambert** [comment]
https://hub.docker.com/_/eclipse-temurin
We don't maintain that image
>Maintained by: [Adoptium](https://github.com/adoptium/containers)
>Where to get help: [Adoptium Slack](https://adoptium.net/slack.html); [Adoptium Support](https://github.com/adoptium/adoptium-support/issues/new/choose)

But it looks like they follow the same support matrix as us https://github.com/docker-library/openjdk/issues/272

Essentially upstream only publishes the JDK
https://github.com/docker-library/openjdk/issues/302#issuecomment-482722509
>Upstream does not distribute an official JRE package that I am aware of, nor do they have documentation for either what bits from the official downloads should be kept or what bits should be removed to create an official JRE package, so this will not involve that. (Folks wishing to create a JRE based on OpenJDK 12+ are likely better off playing with jlink anyhow to create their own custom minimal JRE via a multi-stage build or similar -- I've personally done so via the existing Oracle Linux image with a multi-stage build copying the resulting minimal JRE into a Debian-based image with great success.)
