### ISSUE TITLE
eclipse-temurin: bring back alpine-slim

### ISSUE THREAD

**Issue by egym-vortega** [docker-library/docs#2103]
Adoptopenjdk alpine-slim has a lot of extra tools missing in the current alpine.

Can you bring it back?

**Comment by tianon** [comment]
From https://hub.docker.com/_/eclipse-temurin:

> -	**Where to file issues**:  
> 	[GitHub](https://github.com/adoptium/containers/issues); The [adoptium support](https://adoptium.net/support.html) page has more information on quality, roadmap and support levels for Eclipse Temurin builds;

This is the repository for the documentation for _all_ official images, so the maintainers of each individual image don't typically follow it.
