### ISSUE TITLE
golang's example Dockerfile missing compilation step

### ISSUE THREAD

**Issue by hashtagchris** [docker-library/docs#2109]
https://github.com/docker-library/docs/blob/master/golang/content.md#start-a-go-instance-in-your-app includes a sample Dockerfile that will "compile and run your project":

```dockerfile
FROM %%IMAGE%%:1.17

WORKDIR /go/src/app
COPY . .

RUN go get -d -v ./...
RUN go install -v ./...

CMD ["app"]
```

Two issues:

* There's no `RUN go build -o app` line, and `CMD` doesn't invoke `go run ...`. Compilation was effectively lost in https://github.com/docker-library/docs/pull/1128
* The `CMD` argument should have an explicit path, as the generated executable is not likely to be in `$PATH`.

**Comment by tianon** [comment]
Unfortunately, this section was assuming `$GOPATH`, which in the images is set to `/go`, and the previous behavior of `go install` was to build and install the relevant binary to `$GOPATH/bin`, which _is_ in `$PATH`, so this example did used to work as-is.  We should probably update it with better guidance for (modern) projects using `go.mod`, something like:

```dockerfile
FROM %%IMAGE%%:1.17

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

CMD ["app"]
```
