### ISSUE TITLE
Is it possible to customize the bottom of the file service?

### ISSUE THREAD

**Issue by jw-star** [docker-library/docs#2114]
![image](https://user-images.githubusercontent.com/48782751/152952211-d18489a2-f9d1-498f-9655-57c3dc9b065d.png)

**Comment by jw-star** [comment]
Not the docker version, I know it's in an html, but the docker version, the location of the html is not found

**Comment by wglambert** [comment]
This is the documentation repo, if you're wanting help with [Caddy](https://hub.docker.com/_/caddy) then you can try their community forums https://caddy.community/
