### ISSUE TITLE
How to handle Critical Security Issues of Base Images

### ISSUE THREAD

**Issue by logidru** [docker-library/docs#2122]
Question

We use tomcat base on corretto to build the backend, we build our image nightly with the latest tags.

e.g tomcat:10.0.17-jdk17-corretto.

Last week i noticed that the trivy scanner of our harbor registry displayed those critical issues (expat), and it was also displayed that the problem was already fixed on a newer version of the base image. So the only thing that had to be done would have been to rebuild the tomcat:10.0.17-jdk17-corretto in order to get the base image updated, but that did not happen (yesterday the image as 11 days old).

Today tomcat:10.0.18-jdk17-corretto was published and i guess the problem will be fixed now, but we had to roll out our new version of the software to our clients yesterday (so with the critical bugs). 

Is there any recommendation how to handle such issues. Is there a way to somehow request for a rebuild of the current tomcat image if the base image has critical issues that were already fixed in a newer version? 

Additional Note:

i just rebuilt the images with tomcat:10.0.18-jdk17-corretto and the expat bug is still in there....

![grafik](https://user-images.githubusercontent.com/71891248/158538584-cca33e05-a9fe-4d00-8878-c9176546b414.png)

Note 2: i just noticed that the base image amazonlinux:2 is the problem :-(

Thx for help
Daniel

**Comment by tianon** [comment]
https://github.com/docker-library/official-images/pull/12056 :+1:

**Comment by tianon** [comment]
Doh, nevermind, that's just 2022 :disappointed:

**Comment by tianon** [comment]
Sorry, triple-post time -- this really isn't the right place for this.  This should happen further down the stack (with an `amazonlinux` update).

This is the repository for the documentation (and doesn't contain or influence any of the building code).
