### ISSUE TITLE
Official image page shows unsupported architecture tags

### ISSUE THREAD

**Issue by headius** [docker-library/docs#2126]
The official image pages generated from this repository show clickable tag search links for platforms the image does not support. For example, for JRuby:

<img width="805" alt="Screen Shot 2022-03-31 at 10 43 25" src="https://user-images.githubusercontent.com/10135/161095904-c0d71c54-d820-4219-8b6b-0b1800f44c03.png">

I have been unable to find any way to customize this list, but we have had at least one bug report about unsupported platforms showing up in this tag list: https://github.com/jruby/docker-jruby/issues/78

It seems like this list should not include platforms that are not explicitly supported, but I am unsure how it is being generated.

**Comment by tianon** [comment]
We don't have direct control over those, but I'll ask some folks on the Hub team. :+1:

**Comment by headius** [comment]
@tianon Thank you! It is confusing for me and for our users to have platforms listed there that we don't support.

**Comment by tianon** [comment]
The good news is that these don't show up on https://hub.docker.com/_/jruby anymore!

(The bad news is that they _do_ still show up on https://hub.docker.com/search?q=jruby&image_filter=official :see_no_evil:)

**Comment by headius** [comment]
Well, it's an improvement!

**Comment by yosifkit** [comment]
> The good news is that these don't show up on https://hub.docker.com/_/jruby anymore!
> 
> (The bad news is that they _do_ still show up on https://hub.docker.com/search?q=jruby&image_filter=official 🙈)

This seems to have improved because I don't see any architecture labels on these pages. Closing issue.

**Comment by headius** [comment]
Good news, thanks! Less confusing for the users.
