### ISSUE TITLE
[MediaWiki] Request to include volume specification or otherwise a notice for compose examples dealing with databases

### ISSUE THREAD

**Issue by insertish** [docker-library/docs#2146]
I'll admit this is partly my fault but I can see other people making this mistake too, I setup Mediawiki a good while back and recently went to pull everything down, what I didn't realise is that I didn't have a volume setup for my database. Yes, I shouldn't have rushed the setup and just copy pasted the example, but I'd rather save anyone else from making the same mistake. Needless to say, I lost all my data there.

The relevant section I'm talking about is [in this README](https://github.com/docker-library/docs/tree/master/mediawiki#-via-docker-stack-deploy-or-docker-compose).

I propose either:
- Adding an example volume
- Adding a notice below the example explicitly stating that there is no storage configured for the database

I also quickly glanced and saw that this also applies to the teamspeak image and I assume others too.
If this is a change you're willing to make, I'd be happy to go through and make a PR using one of the two solutions.

**Comment by legoktm** [comment]
@wglambert adding a volume to the example so people can just copy/paste it would be great IMO!
