### ISSUE TITLE
[php]: Inconsistent php versions

### ISSUE THREAD

**Issue by khusseini** [docker-library/docs#2193]
We are using the `php:8.0.13-fpm-alpine3.14` as a base image.
Using the image as is works fine, however whenever we install any of the following packages, results in PHP v8.0.16 bein installed alongside 8.0.13.

```
    php8-pecl-imagick \
    imagemagick \
    php8-bcmath \
    php8-bz2 \
    php8-ctype \
    php8-curl \
    php8-exif \
    php8-fileinfo \
    php8-ftp \
    php8-gd  \
    php8-gmp \
    php8-iconv \
    php8-intl \
    php8-json \
    php8-mbstring \
    php8-opcache \
    php8-openssl \
    php8-pdo \
    php8-pdo_mysql \
    php8-mysqli \
    php8-posix \
    php8-redis \
    php8-simplexml \
    php8-soap \
    php8-tidy \
    php8-tokenizer \
    php8-xml \
    php8-xmlreader \
    php8-xmlwriter \
    php8-xsl \
    php8-zip \
    php8-zlib \
    php8-phar \
    php8-sockets \
 ```
It has a bad sideeffect, that FPM and CLI have two different versions and configuraitons. 

Is there anyway to consitently install PHP in alpine using only one version?

**Comment by wglambert** [comment]
If you use the distro's repos to install modules it won't detect the existing compiled php and will grab the latest version of php as a dependency

See https://github.com/docker-library/docs/tree/master/php#how-to-install-more-php-extensions
