### ISSUE TITLE
how to deploy using a custom domain?

### ISSUE THREAD

**Issue by d3netxer** [docker-library/docs#2194]
Reading the documentation I run the following command using docker locally and it works. I can visit Geonetwork here: http://localhost:8080/geonetwork

```
docker run --name some-geonetwork -d -p 8080:8080 geonetwork:3.12.6
```

However I then try running the same command on my Ubuntu based server, but Geonetwork does not show up when I visit the domain of the server: http://xx.xxx.xxx.xx:8080/geonetwork

any help?

**Comment by tianon** [comment]
I think this would probably be more appropriately filed either on https://github.com/geonetwork/docker-geonetwork or even better a support-focused forum of some kind.

(This repository is the generic repository for all the official images documentation.)
