### ISSUE TITLE
eclipse-temurin example runs jar as root user instead of specific non-root user

### ISSUE THREAD

**Issue by OlafMeuwese** [docker-library/docs#2223]
As far as I know, running your application as root user is considered suboptimal from a security standpoint. 
I think it might be an improvement if this example shows how to run it as a non-root user. This will send most users on the right path.

In addition, it now runs on version 11, this might be increased to 17 as being it being the latest LTS release

**Comment by tianon** [comment]
cc @gdams @sxa (`eclipse-temurin` image maintainers)

**Comment by OneCricketeer** [comment]
You can use `nobody`, assuming you don't need access to other files copied or mounted 

https://stackoverflow.com/questions/72562483/is-it-safe-to-run-openjdk-images-like-eclipse-temurin-as-root
