### ISSUE TITLE
jetty/README.md: Obsolete information about HTTP/2 vs OpenJDK 9 availability

### ISSUE THREAD

**Issue by PerMildner** [docker-library/docs#2226]
[docs/jetty/README.md](https://github.com/docker-library/docs/blob/master/jetty/README.md#http2-support) says "Once OpenJDK 9 becomes generally available with built-in support for ALPN, this image will be updated".

This needs updating since OpenJDK 9 has now been generally available for a long time.

**Comment by tianon** [comment]
cc `jetty` image maintainers: @gregw @lachlan-roberts @olamy @joakime
