### ISSUE TITLE
How is for example "ubuntu" built now?

### ISSUE THREAD

**Issue by matti** [docker-library/docs#2227]
Before September, 2022 the https://hub.docker.com/r/library/ubuntu/ was built like this:

1. This line https://github.com/tianon/docker-brew-ubuntu-core/blob/490e0e86ec5c93524b7ae37b79025e5ded5efcc6/bionic/Dockerfile#L2
 added `ubuntu-bionic-core-cloudimg-amd64-root.tar.gz` 

2. That tarball was in the same repositoryhttps://github.com/tianon/docker-brew-ubuntu-core/tree/490e0e86ec5c93524b7ae37b79025e5ded5efcc6/bionic

3. The readme in @tianon repo (https://github.com/tianon/docker-brew-ubuntu-core/blob/1abcdfbe8e5292dd79bec0e3d5ad9fadddcc9eb1/CONTRIBUTING.md) stated that "Some Jenkins happens" (somewhere, apparently in https://doi-janky.infosiftr.net/)

4. And then the README states that "The new images are published on https://hub.docker.com/"

So, before this September2022 refactoring I couldn't figure out exactly where it's pushed. Eg. how can I know that it's not just pushed from some random laptop somewhere in Starbucks?

And now, after the refactoring the process is more formalised, but it's not clear.

**Comment by tianon** [comment]
Oops, images are maintained in https://git.launchpad.net/cloud-images/+oci/ubuntu-base now :+1:

@woky @mwhudson, we probably need to update https://github.com/docker-library/docs/tree/master/ubuntu :eyes:

(for a view of the "larger" process for all official images, see https://github.com/docker-library/faq#an-images-source-changed-in-git-now-what)

**Comment by mwhudson** [comment]
Oops yes. I don't know enough about the new system to write sensibly about it though!

**Comment by woky** [comment]
> Oops yes. I don't know enough about the new system to write sensibly about it though!

I do. :-) Let me create the PR today.

**Comment by matti** [comment]
@woky thank you - the references don't really answer the question asked here tho - How is everything built, eg. since the image is not signed, is there any public trace to actually know what goes in and where?

**Comment by woky** [comment]
Ubuntu OCI image on Docker Hub is built from rootfs tarball and Dockerfile that's in the repo in the updated documentation. I don't have enough understanding about this process but READMEs at https://github.com/docker-library/bashbrew/ and https://github.com/docker-library/official-images, and https://doi-janky.infosiftr.net/ Jenkins are good starting points.

The rootfs tarball is built by [live-build](https://launchpad.net/ubuntu/+source/live-build). These builds are triggered by Jenkins pipelines that are not publicly browseable, but they only glue public Launchpad builds and do testing and publishing. Here's an example of a rootfs tarball of focal is built on Launchpad: https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/focal/ubuntu-oci/+build/381265. Currently it is not straightforward to go from an Ubuntu OCI image to a Launchpad build, but that should change in the future.

As for SBOM, Ubuntu images currently don't have any, but will have it in future.

**Comment by cjdcordeiro** [comment]
> @woky thank you - the references don't really answer the question asked here tho - How is everything built, eg. since the image is not signed, is there any public trace to actually know what goes in and where?

@woky is right. 

These are the important references when it comes to what has been built and where (with logs):

[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/jammy/ubuntu-oci)	Jammy	on 2021-10-19
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/impish/ubuntu-oci)	Impish	on 2021-04-30
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/focal/ubuntu-oci)	Focal	on 2021-05-19
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/groovy/ubuntu-oci)	Groovy	on 2021-05-18
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/kinetic/ubuntu-oci)	Kinetic	on 2022-04-27
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/lunar/ubuntu-oci)	Lunar	on 2022-10-31
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/bionic/ubuntu-oci)	Bionic	on 2021-05-11
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/xenial/ubuntu-oci)	Xenial	on 2021-05-27
[ubuntu-oci](https://launchpad.net/~cloud-images-release-managers/+livefs/ubuntu/hirsute/ubuntu-oci)	Hirsute	on 2021-05-06

---

@woky maybe we could include this table in the docs?
