### ISSUE TITLE
Provide arm64 image for `*-alpine` ?

### ISSUE THREAD

**Issue by abcfy2** [docker-library/docs#2243]
I find `*-alpine` only has `amd64` arch, like `11-jdk-alpine`. Would you please also provide arm64 arch ?

**Comment by wglambert** [comment]
The OpenJDK image is officially deprecated, but there are other Official Image alternatives
https://github.com/docker-library/docs/tree/master/openjdk#deprecation-notice
https://github.com/docker-library/openjdk/issues/505
