### ISSUE TITLE
Mariadb on Docker got:[Entrypoint]: Stopping temporary server 

### ISSUE THREAD

**Issue by Tarekdu13** [docker-library/docs#2251]
`Server: Docker Engine - Community`
**Engine:**
**Version:** 20.10.22
**API version:** 1.41 (minimum version 1.12)
**Go version:** go1.18.9
**Git commit:** 42c8b31
**Built:** Thu Dec 15 22:25:49 2022
**OS/Arch:** linux/amd64
**Experimental:** false
**containerd:**
**Version:** 1.6.14
**GitCommit:** 9ba4b250366a5ddde94bb7c9d1def331423aa323
**runc:**
**Version:** 1.1.4
**GitCommit:** v1.1.4-0-g5fd4c4d
**docker-init:**
**Version:** 0.19.0
**GitCommit:** de40ad0
**Container image:** mariadb:10.9.4

I'am running an app that uses a backup of an old database, so i wanted to try it out first with docker-compose.yml but everytime i got this error:
```
[Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql 
2022-12-21 11:10:54+00:00 [Note] [Entrypoint]: Stopping temporary server 
2022-12-21 11:10:54 0 [Note] mariadbd (initiated by: unknown): Normal shutdown
```

Then is starts normaly but without my backup of the database.

**Comment by Tarekdu13** [comment]
got:
I'am running an app that uses a backup of an old database, so i wanted to try it out first with docker-compose.yml but everytime i got this error: 
[Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql   2022-12-21 11:10:54+00:00 [Note] [Entrypoint]: Stopping temporary server 2022-12-21 11:10:54 0 [Note] mariadbd (initiated by: unknown): Normal shutdown

**Comment by tianon** [comment]
From https://hub.docker.com/_/mariadb: :eyes:

> -	**Where to get help**:  
> 	[Database Adminstrators (Stack Exchange)](https://dba.stackexchange.com/questions/tagged/docker+mariadb), [MariaDB Knowledge Base](https://mariadb.com/kb/en/docker-and-mariadb/) ([Ask a Question here](https://mariadb.com/kb/en/docker-and-mariadb/ask) available).
> 
> Also see the ["Getting Help with MariaDB" article on the MariaDB Knowledge Base](https://mariadb.com/kb/en/getting-help-with-mariadb/).
> 
> ...
> 
> -	**Where to file issues**:  
> 	Issues can be filed on [https://jira.mariadb.org/](https://jira.mariadb.org/) under the "MDEV" Project and "Docker" Component, or on [GitHub](https://github.com/MariaDB/mariadb-docker/issues)
