### ISSUE TITLE
[InfluxDB] manual setup won't work without --force flag in recent versions

### ISSUE THREAD

**Issue by innomatica** [docker-library/docs#2272]
[Manual setup command](https://github.com/docker-library/docs/tree/master/influxdb#manual-setup) yields following error in version 2.6.1
```
Error: Setup was canceled
```
To prevent the error you need to include `--force` flag
```
$ docker exec influxdb2 influx setup \
      --username $USERNAME \
      --password $PASSWORD \
      --org $ORGANIZATION \
      --bucket $BUCKET \
      --force
```

**Comment by tianon** [comment]
cc `influxdb` maintainers: @bnpfeife @jeffreyssmith2nd
