### ISSUE TITLE
Automake anchor links

### ISSUE THREAD

**Issue by danepowell** [docker-library/docs#2304]
I frequently have to link to Docker library docs. On [long pages like for the PHP image](https://hub.docker.com/_/php), it would be really nice to be able to link to a specific heading.

For instance, GitHub automakes anchor links, such as for the PHP README: https://github.com/docker-library/docs/blob/master/php/README.md#how-to-install-more-php-extensions

But the docs on hub.docker.com are missing such anchors.

**Comment by tianon** [comment]
The rendering engine used for the markdown on Docker Hub has changed several times, and I don't think it's always consistently supported anchors.  When I need an anchor, I usually link to the canonical version of the docs on GitHub instead :sweat_smile:

**Comment by tianon** [comment]
See also https://github.com/docker/hub-feedback/issues/956
