### ISSUE TITLE
https://hub.docker.com/_/geonetwork

### ISSUE THREAD

**Issue by k-eight-v** [docker-library/docs#2311]
On this site is info about v3, but i need info about v4. Cause v4 does no come up with this command: docker run --name some-geonetwork -d -p 8080:8080 geonetwork

**Comment by tianon** [comment]
cc @doublebyte1 @juanluisrp

**Comment by doublebyte1** [comment]
> Indeed there isn't documentation about how to run GN4 there yet. However you can find a docker-compose.yml file with an example at https://github.com/geonetwork/docker-geonetwork/blob/main/4.2.2/docker-compose.yml.
> 
> Some more info in the [README.md](https://github.com/geonetwork/docker-geonetwork/tree/main/4.2.2#running-with-remote-elasticsearch).

@juanluisrp  +1 for providing an example.

 A small suggestion: if you are proxying everything through nginx, maybe you don't need to publish the elastic and geonetwork ports, [here](https://github.com/geonetwork/docker-geonetwork/blob/main/4.2.2/docker-compose.yml#L133) and [here](https://github.com/geonetwork/docker-geonetwork/blob/main/4.2.2/docker-compose.yml#L133)?
