### ISSUE TITLE
eclipse-temurin  - New JDK release 17.0.7

### ISSUE THREAD

**Issue by jasonjckn** [docker-library/docs#2319]
can we get docker eclipse-temurin builds for the latest JDK 17.0.7 please?

**Comment by yosifkit** [comment]
This is only the repo for the Docker Official Images' docs. With https://github.com/adoptium/containers/pull/380, it seems like they have most of the `17.0.7` architectures in their Dockerfiles. We'll likely see a PR to https://github.com/docker-library/official-images soon, but that is up to the [image maintainers](https://github.com/docker-library/official-images/blob/c642268ed9e0120d827d2185e28ae512e3bab68c/library/eclipse-temurin#L3-L4) when they send us a PR with Dockerfile updates.

># Quick reference
>
>-	**Maintained by**:  
>	[Adoptium](https://github.com/adoptium/containers)
>
>-	**Where to get help**:  
>	[Adoptium Slack](https://adoptium.net/slack); [Adoptium Support](https://github.com/adoptium/adoptium-support/issues/new/choose)

(from:  https://github.com/docker-library/docs/tree/fcd350a604f3cc6fe385db587fe215bd74898943/eclipse-temurin#quick-reference)
