### ISSUE TITLE
README.md typo (missing space after flag)

### ISSUE THREAD

**Issue by Shadow8472** [docker-library/docs#2365]
[https://github.com/docker-library/docs/blob/master/mariadb/README.md#connect-to-mariadb-from-the-mysqlmariadb-command-line-client](https://github.com/docker-library/docs/blob/master/mariadb/README.md#connect-to-mariadb-from-the-mysqlmariadb-command-line-client)

-hsome-mariadb

should be

-h some-mariadb

I noticed this on DockerHub.

**Comment by Shadow8472** [comment]
and

-uexample-user

should be 

-u example-user

**Comment by Shadow8472** [comment]
Never mind. I'm just a confused fool who hasn't learned mysql yet.

**Comment by yosifkit** [comment]
No worries, `mysql` command line is a bit unique in its flag parsing.
