### ISSUE TITLE
php:fpm needs better documentation

### ISSUE THREAD

**Issue by tianon** [docker-library/docs#238]
I couldn't find a docs issue specifically regarding `php:fpm` lacking good docs, so I'm creating this to try and catalyze that a little better.

Useful information:
- [the `wordpress:fpm` `Dockerfile`](https://github.com/docker-library/wordpress/blob/939fefa77f68928d19750760023af7dfe48828c8/fpm/Dockerfile)
- https://github.com/docker-library/php/issues/54#issuecomment-72306590

**Comment by beingalink** [comment]
I created a [gist](https://gist.github.com/beingalink/fe8f1425e1b6268fe996) describing my configuration. It uses an owncloud:fpm container, a mysql container, a redis container and nginx installed directly on the host. Comments about possible improvements, misconceptions, etc. are welcome.

**Comment by tianon** [comment]
Nice!  It's probably also worth pointing out @md5's work in this area WRT wordpress: https://gist.github.com/md5/d9206eacb5a0ff5d6be0

**Comment by schmunk42** [comment]
We're playing around with [nginx added to the fpm image](https://github.com/dmstr/docker-php-yii2/blob/master/nginx/Dockerfile-fpm-nginx) and running both processes with forego then.

The base PHP-fpm image can still be used with a separate nginx container.

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/1366/files#diff-08abf6630ef4e127953e2e4426f310e7 :tada:
