### ISSUE TITLE
golang: custom import paths

### ISSUE THREAD

**Issue by yosifkit** [docker-library/docs#24]
Add docs for the magic godir (mention go-wrapper?)

Added here: https://github.com/docker-library/golang/pull/10

**Comment by tianon** [comment]
`.godir` is a great hack, but Go 1.4 added Custom Import Paths that we now prefer instead: https://golang.org/s/go14customimport

**Comment by yosifkit** [comment]
We don't support golang versions older than `1.4` now, so we can remove the "undocumented `.godir`". :smiling_imp:
