### ISSUE TITLE
Version tags for additional packages

### ISSUE THREAD

**Issue by unf0rg0tt3n** [docker-library/docs#2405]
Hi,

I'm using external storage in my nextcloud server (which gets auto updated by sheppard). Every time the container updates the external storage gets broken.

Would it be an idea to include version tags like the fpm and latest tags, like; :latest-smbclient or something? Or is it a possibility to include it in the latest version?

Is there also a workaround to at least fix this for me?

I've read that lots of people ask about this but it's all the same message: "you can install by..." 

Thanks!

**Comment by tianon** [comment]
It sounds like you need additional software in your container image -- for that, I'd suggest writing yourself a short `Dockerfile` that installs the software you need on top of `nextcloud` and automating rebuilds/redeploys of _that_ instead of `nextcloud` directly/raw.
