### ISSUE TITLE
mariadb logo change, in repo, not on hub

### ISSUE THREAD

**Issue by grooverdan** [docker-library/docs#2407]
Like #1592 the MariaDB logo change in e3bbc03c7cb6f81d5c6a29d327bbfb05e017f743 didn't propagate to the https://hub.docker.com/_/mariadb/.

**Comment by tianon** [comment]
:sob: this should've worked, I'm sorry!

I've raised this with the appropriate team in Docker -- hopefully we can get it resolved quickly. :bow:

**Comment by tianon** [comment]
Good news!  The team identified the bug, but it's probably going to be at least Monday before they can properly test/deploy the fix. :+1:

**Comment by grooverdan** [comment]
Thanks. Have a good weekend.

**Comment by grooverdan** [comment]
Confirmed. Thanks @whalelines

**Comment by whalelines** [comment]
Thanks go to @tianon and @benja-M-1, not me.
