### ISSUE TITLE
Error in https://hub.docker.com/r/amd64/ros

### ISSUE THREAD

**Issue by FHefterSRH** [docker-library/docs#2456]
In several places on the page there is an error in the line

```CMD ["ros2", "launch", "demo_nodes_cpp", "talker_listener.launch.py"]```

Solution:

Change

```talker_listener.launch.py```

to

```talker_listener_launch.py```

Then the examples work.

The files to make the change in are as follows:

ros/content.md (line 25,105,220)

ros/README.md (line 87,167)

Edit:

The file to which the demo refers is located in the folder
https://github.com/ros2/demos/tree/rolling/demo_nodes_cpp/launch/topics
It was changed last year.

I searched for the misspelled name and found many other places on Github where it still exists. So a single PR is not enough.

**Comment by tianon** [comment]
Good catch!  A PR to update https://github.com/docker-library/docs/blob/42ae663b4b922326e5c55c7c513c8d04a11f9aaf/ros/content.md would probably be appreciated by the `ros` image maintainer (@tfoote) :eyes:

**Comment by tfoote** [comment]
Yes we changed our recommended pattern and missed the update here. https://github.com/ros2/ros2_documentation/pull/3166 This is now current for all the active distros so we don't need to do a conditional changeover.
