### ISSUE TITLE
PostgreSQL 17: Best way to update docker container postgresql

### ISSUE THREAD

**Issue by SimonBard** [docker-library/docs#2510]
My docker container does not start since the update to Postgresql 17. Container was automatically updated by watchtower. 
What is the best way to update the database?

One way I imagine is to start a container with older version on another port and from within the container, do 
`pg_dumpall -p 5432 | psql -d postgres -p 5433`

I have no clue if this works or not, but could not find anything in the docu.

**Comment by tianon** [comment]
Closing in favor of https://github.com/docker-library/postgres/issues/1293
