### ISSUE TITLE
PostgreSQL: perl environment variables incomplete for pg_restore, psql -> LANGUAGE = (unset), LC_ALL = (unset)

### ISSUE THREAD

**Issue by KinastPR** [docker-library/docs#2515]
Causes problems on macOS when importing. And likely some other setups.

_**LANGUAGE = (unset),
LC_ALL = (unset),**_

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "de_DE.UTF-8",
	LANG = "en_US.utf8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

**Comment by tianon** [comment]
This repository contains the source for Docker Official Image (DOI) documentation and is not a general resource for running PostgreSQL or Docker.

You can ask for help in the [Docker Community Slack](https://dockercommunity.slack.com/). If you are not already a member of the Docker Community Slack, you can use [this link to join](http://dockr.ly/comm-slack). You can find more support options at [Docker Support](https://www.docker.com/support/).

**Comment by KinastPR** [comment]
> This repository contains the source for Docker Official Image (DOI) documentation and is not a general resource for running PostgreSQL or Docker.

That's precisely why I posted an issue with the official Docker Image of PostgreSQL. Because this _is_ an issue with the official Docker Image of PostgreSQL. The error occurs within containers built from the official Docker Image. So this is the precise place for this report, is it not? ... I've clarified the details in the original issue to avoid any future misunterstanding.

Please re-open this issue. Thanks.

**Comment by tianon** [comment]
Sorry, there's still some missing information -- what is it you're trying to do?  What have you tried?  What did you expect to happen and what happens instead?  Do you have a minimal reproducer?  With the report as-is, I can't direct you to where the "fix" might be -- all we've got are some logs without much context, and even those are only warnings not errors.  Is there a concrete problem being caused by these warnings?  (These look like they're warnings from APT or a process APT invokes, not PostgreSQL.)

**Comment by KinastPR** [comment]
I'm running **_psql_** on the container. It throws the aforementioned perl warning. All it needs is for the Docker Image to provide for the environment variables LANGUAGE and  LC_ALL. Preferably with language and locale that actually is _present_ in the image. Obviously.

I suggest just setting _LANGUAGE=en_ and _LC_ALL=en_US.utf8_ in the Docker Image. That's all. AFAICT that language and the locale already are present in the image. They appear to be the default.

Otherwise it's a huge hassle on getting those to be available everywhere in the container without editing configs and reloading them manually on a running container. Not fun. To put it mildly.

**Comment by tianon** [comment]
The `postgres` image already defaults to the `en_US.utf8` locale: https://github.com/docker-library/postgres/blob/15778149223e016ba1bd43db00825226ddc821a4/17/bookworm/Dockerfile#L52-L64

See also https://github.com/docker-library/docs/blob/77c9ff6832aa4e736874176b6daa992516b12e4f/postgres/README.md#locale-customization for where we document how to add/use a different locale.

**Comment by tianon** [comment]
```console
$ docker run -dit --name pg --pull=always --env POSTGRES_PASSWORD=foo postgres:17
17: Pulling from library/postgres
Digest: sha256:fe4efc6901dda0d952306fd962643d8022d7bb773ffe13fe8a21551b9276e50c
Status: Image is up to date for postgres:17
80a90b09dcc6abba3b3684d4800226033abefd455eb004becf4a818c1d3adf5a

$ docker exec pg psql -U postgres -l
                                                    List of databases
   Name    |  Owner   | Encoding | Locale Provider |  Collate   |   Ctype    | Locale | ICU Rules |   Access privileges   
-----------+----------+----------+-----------------+------------+------------+--------+-----------+-----------------------
 postgres  | postgres | UTF8     | libc            | en_US.utf8 | en_US.utf8 |        |           | 
 template0 | postgres | UTF8     | libc            | en_US.utf8 | en_US.utf8 |        |           | =c/postgres          +
           |          |          |                 |            |            |        |           | postgres=CTc/postgres
 template1 | postgres | UTF8     | libc            | en_US.utf8 | en_US.utf8 |        |           | =c/postgres          +
           |          |          |                 |            |            |        |           | postgres=CTc/postgres
(3 rows)
```

**Comment by KinastPR** [comment]
> The `postgres` image already defaults to the `en_US.utf8` locale

Yes, I know. I just said the exact same thing.
HOWEVER, the environment variables _LANGUAGE_ and _LC_ALL_ are _not_ set.
Only _LC_CTYPE_ and _LANG_ are.
Which isn't sufficient in the aforementioned case/issue.

And as pointed out this is about the _**Docker Image**_(!!) for PostgreSQL, _not_ the DBMS PostgreSQL that runs on it.

**Comment by tianon** [comment]
Sure, but why would we set `LANGUAGE` or `LC_ALL`? (We also don't set `LC_CTYPE`.)  Can you please elaborate on the use case that requires setting `LANGUAGE` or `LC_ALL` in addition to `LANG`?  What is it you're actually trying to accomplish?

**Comment by KinastPR** [comment]
The usecase is running the PostgreSQL CLI tools on the Docker Image. Since those are the tools that belong to the exact same version of the DBMS it's not unplausible to run them in the respective container.
...
Especially and more so when on a foreign OS that has to emulate x86 in order to run the container.
...
Like, for instance, in my case, macOS on arm64 ("Apple Silicon"). Docker for macOS uses Apples Rosetta x86 emulation layer to run Docker and its containers, which is a whole different bunch of fun of which I will spare you the details as not to traumatize you with tales of my epic plight.

**Comment by yosifkit** [comment]
So, how are you running `pg_restore` or `psql` and your initial `postgres` container? I've run both commands and not seen the same errors.

Running `postgres` or some (most?) of the `pg_*` commands with a different `LANG` or `LC_*` set requires the `localdef` as described in https://github.com/docker-library/docs/blob/77c9ff6832aa4e736874176b6daa992516b12e4f/postgres/README.md#locale-customization.

**Comment by LaurentGoderre** [comment]
@KinastPR it would be a lot less problematic to set those variables at container creation time than for the official image to impose defaults on everyone.

**Comment by KinastPR** [comment]
My take on this is a little different. These appear to be default env-vars that perl expects, so I see no fault in setting them right in the image. But that's just me. Y'all are the maintainers so it's your call in the end.

Thanks for the help and the good work providing postgres containers anyway.
