### ISSUE TITLE
method Pluck is no longer available in Mojo:5.80

### ISSUE THREAD

**Issue by nghiant2710** [docker-library/docs#294]
Pluck is used in push.pl but it had been removed since Mojo:5.73: https://github.com/kraih/mojo/blob/master/Changes#L237

Can you guys update this?

**Comment by md5** [comment]
https://github.com/kraih/mojo/blob/master/Changes#L342

>   - Deprecated Mojo::Collection::pluck in favor of Mojo::Collection::map.

**Comment by tianon** [comment]
Crackers.  Thanks for the heads up, we'll get to work fixing this. :innocent:
