### ISSUE TITLE
/var/lib/ghost/apps permission denied?

### ISSUE THREAD

**Issue by FreedomKnight** [docker-library/docs#307]
Hi, I run this command

```
sudo docker run --name ghost -p 8080:2368 -v /path/tot/Ghost:/var/lib/ghost ghost
```

and it told me 

```
mkdir: cannot create directory '/var/lib/ghost/apps': Permission denied
```

is it cannot use sudoer to run it ? (because fedora default let me use sudoer)
or something else wrong?

**Comment by md5** [comment]
It sounds like you're running under VirtualBox and the underlying `/path/to/Ghost` can't actually be `chown`'d. The entrypoint already has code to `chown` the whole `/var/lib/ghost` directory: https://github.com/docker-library/ghost/blob/master/docker-entrypoint.sh#L22
