### ISSUE TITLE
Update to documentation: --privileged not needed any longer for CentOS with systemd?

### ISSUE THREAD

**Issue by beetree** [docker-library/docs#308]
This file: https://github.com/docker-library/docs/tree/master/centos

States that to run CentOS with `systemd` you need `--privileged`. It seems to work without this in:

```
docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

Alternatively, [this](http://www.brad-x.com/2014/12/27/running-systemd-within-a-docker-image/) article claims that `--cap-add=SYS_ADMIN` is a sufficient replacement of `--privileged`

Am I missing something or is the documentation out of date?

Thanks!

EDIT: To be clear, in my testing, not even `--cap-add=SYS_ADMIN` is necessary.

**Comment by tianon** [comment]
cc @jperrin

**Comment by jperrin** [comment]
The documentation is out of date, however there are some bits of systemd that require more capabilities than the default. --cap-add=SYS_ADMIN should be sufficient. I'll see about correcting the documentation.

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/docs/pull/439. :+1:
