### ISSUE TITLE
Debian Dockerfiles not under docker-library?

### ISSUE THREAD

**Issue by ruudud** [docker-library/docs#317]
Why is the documentation for the official Debian images located here, but pointing at https://github.com/tianon/docker-brew-debian for the actual Dockerfiles?

Shouldn't it be a separate repository under docker-library like most of the other stuff?

(Yes, I have noticed that tianon is a contributor to this repository as well, but IMO it *feels better* if it's all under one umbrella.)

**Comment by Moghedrin** [comment]
Most (if not all) official images that are maintained by upstream (nginx, perl) or dedicated community members (haskell, debian, ubuntu) live outside docker-library.

That the Debian/Ubuntu images live outside docker-library is indicative that Tianon maintains those separately from his role as one of the official-images maintainers.

It's never been the intention that all images are "under one umbrella", but rather that all proposed images are reviewed and curated before becoming "Official Images" to maintain a high standard of quality and consistency.

**Comment by yosifkit** [comment]
The debian images are especially separate since they are maintained by upstream, ie Debian Developers (@tianon being one of them), rather than the `docker-library` team.  Though documentation for all official images is housed in this repo for ease of updates and keeping consistency.

**Comment by ruudud** [comment]
Thanks for clarifying, guys. Keep up the good work!
