### ISSUE TITLE
Official repos missing "Full Description" on Docker Hub

### ISSUE THREAD

**Issue by davidcurrie** [docker-library/docs#365]
As of today, all of the official repos on Docker Hub appear to be missing their full description. Just reads "Full description is empty for this repo."

**Comment by tianon** [comment]
Yeah, it's a bug in the Hub (for example, see https://hub.docker.com/_/wordpress/ vs https://hub.docker.com/r/library/wordpress/).  @cpuguy83 notified the Hub team and they're working on figuring out what's going on. :+1:

**Comment by tianon** [comment]
This appears to be fixed!  Can anyone else confirm that it's not some strange cache artifact on my machine? :pray: :innocent:

**Comment by cpuguy83** [comment]
LGTM

**Comment by tianon** [comment]
Woooot!  :+1: :dancer:
