### ISSUE TITLE
Golang tip image

### ISSUE THREAD

**Issue by gravis** [docker-library/docs#371]
It would be nice to have a "tip" golang image, to test against nightly builds.
See: https://github.com/mattes/migrate/pull/54
We need docker to make contributors life easier, but we're losing the ability to test against tip in travis.

**Comment by tianon** [comment]
This issue would be more appropriate over on https://github.com/docker-library/golang, but I'd note that the official images don't really have a mechanism to support automated builds, so the best we could do is a rough snapshot of Go tip periodicially, and that this is a request that's likely better served by some means other than the official images.
