### ISSUE TITLE
HTTP2 doesn't work

### ISSUE THREAD

**Issue by hex6ng** [docker-library/docs#379]

**Comment by md5** [comment]
Which image are you referring to?

**Comment by hex6ng** [comment]
nginx:1.9.5, nginx:1.9.6

**Comment by md5** [comment]
You'll have better luck reporting that at https://github.com/nginxinc/docker-nginx/issues

They're probably going to want some more detail about your configuration, how you're trying to test HTTP2, and what behavior you're seeing.
