### ISSUE TITLE
Enabling SSL

### ISSUE THREAD

**Issue by drpain** [docker-library/docs#383]
I have been trying to find the answer buy I am quite confused. How exactly do I enable Elastic Search to talk over SSL.

IE: https://localhost:9200 ??

I am super confused at the moment.

**Comment by yosifkit** [comment]
It shouldn't be anything different than what is described on their site: https://www.elastic.co/guide/en/shield/current/ssl-tls.html.  The only difference it that you probably want to generate them once and then mount in the keys and an `elasticsearch.yml` to use them.

**Comment by drpain** [comment]
I am pretty bad at generating that x503 cert. I ended up just reverse proxing via ngiinx
