### ISSUE TITLE
MySQL container is taking too much memory

### ISSUE THREAD

**Issue by Lev09** [docker-library/docs#391]
Hi, I am using **MySQL** container for **WordPress** site. My problem is that MySQL container is using too much memory, about **500MB**. Is there any way to decrease memory usage ?

Thanks.

**Comment by yosifkit** [comment]
A user had suggested a blog that had information about minimizing the memory usage: https://github.com/docker-library/mysql/issues/3#issuecomment-59223288.  One way will be to mount in your custom `mysql.cnf` into `/etc/mysql/conf.d/`; or create a Dockerfile and `COPY` in the config.
