### ISSUE TITLE
how to pass a new startup option like --log-raw

### ISSUE THREAD

**Issue by stayliv3** [docker-library/docs#407]
mysql image。i want to change the start options .add the --log-raw option. is there a way to do that？ thanks

**Comment by yosifkit** [comment]
If that is a flag to `mysqld`, then just add it to the run `docker run ... mysql --log-raw`.  Anything after the image that you are going to run becomes arguments to `mysqld` (as long as it starts with a `-`, otherwise the entrypoint will try to run what is passed like `bash`).

**Comment by stayliv3** [comment]
thanks。--log-raw is a flag to `<mysqld>`. It solved my question.
