### ISSUE TITLE
Docker build Error response from daemon: Cannot start container <ID>: Cannot mkdir: /var/www is not a directory

### ISSUE THREAD

**Issue by quanenmin** [docker-library/docs#424]
Cannot start container,the steps:

[root@localhost test]# cat Dockerfile 
FROM php
ADD index.php /var/www
EXPOSE 8080
WORKDIR /var/www
ENTRYPOINT ["php","-S","0.0.0:8080"]	

[root@localhost test]# docker build -t test/helloworld .
Sending build context to Docker daemon 3.072 kB
Sending build context to Docker daemon 
Step 0 : FROM php
 ---> 1b72f5b90bbd
Step 1 : ADD index.php /var/www
 ---> 4aaaa61ea373
Removing intermediate container 537f95562abb
Step 2 : EXPOSE 8080
 ---> Running in 32c15f1064ac
 ---> 4c344afb0511
Removing intermediate container 32c15f1064ac
Step 3 : WORKDIR /var/www
 ---> Running in 4ce2d5321941
 ---> dccf15a79702
Removing intermediate container 4ce2d5321941
Step 4 : ENTRYPOINT php -S 0.0.0:8080
 ---> Running in 63460aa3cf10
 ---> e45ccd89dd76
Removing intermediate container 63460aa3cf10
Successfully built e45ccd89dd76

[root@localhost test]# docker run -d -p 8080:8080 test/helloworld
3fd618414d8410aa74c9dabcbf73960f035f4c5a6fa3d4c995165730d3b7cc1d
Error response from daemon: Cannot start container 3fd618414d8410aa74c9dabcbf73960f035f4c5a6fa3d4c995165730d3b7cc1d: Cannot mkdir: /var/www is not a directory

[root@localhost test]# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64

[root@localhost test]# uname -a
Linux localhost 3.10.93-1.el6.elrepo.x86_64 #1 SMP Tue Nov 10 13:45:47 EST 2015 x86_64 x86_64 x86_64 GNU/Linux

please help me , Thank you very much .

**Comment by yosifkit** [comment]
I think this should fix it (looks like it was copying `index.php` to a file called `www`):
```diff
-ADD index.php /var/www
+ADD index.php /var/www/
```

**Comment by quanenmin** [comment]
@yosifkit  thank you for your answer . I test, but cannot resolve it.

**Comment by yosifkit** [comment]
It looks like this problem is resolved, please reply if this was closed in erroneously.

**Comment by suifengpiao14** [comment]
i get the same problem ，and try to change 
`ADD index.php /var/www`
to
`ADD index.php /var/www/`
to resolve it 
thanks
