### ISSUE TITLE
golang: super slim runtime

### ISSUE THREAD

**Issue by yosifkit** [docker-library/docs#43]
Document the ability to use a tar from standard in to make a super slim runtime image with just the needed binary.

**Comment by tianon** [comment]
@jpetazzo wrote a thing! https://jpetazzo.github.io/2016/09/09/go-docker/ :heart:

**Comment by tianon** [comment]
I believe this is officially deprecated by multi-stage builds (since it's no longer required to dance with tars if you're OK with multi-stage builds, and anyone who isn't is savvy enough to know how to do the tar dance). :metal:
