### ISSUE TITLE
Jenkins can't run git: unable to look up current user in the passwd file: no such user

### ISSUE THREAD

**Issue by ggeorgovassilis** [docker-library/docs#437]
When setting up a project that needs to clone a git repository, cloning will fail with this message:

```unable to look up current user in the passwd file: no such user```

I exec'd into the container trying to clone the repository which fails with the same error message. It turns out the user it is running with isn't set up correctly (no entry in /etc/passwd).

I'm using this Dockerfile to fix the user:
```yaml
FROM jenkins:1.625.3
USER root
RUN chmod 644 /etc/nsswitch.conf
RUN adduser consoleuser --uid 1002 --home /home/consoleuser --disabled-password
USER jenkins
```
Reported against 1.652.3

**Comment by yosifkit** [comment]
I think this issue would be better over on https://github.com/jenkinsci/docker/; ping @carlossg.

**Comment by carlossg** [comment]
Yes, it should be in the jenkinsci repo, but anyway the user is in the passwd file

    $ docker run -ti jenkins:1.625.3 grep jenkins /etc/passwd
    jenkins:x:1000:1000::/var/jenkins_home:/bin/bash

**Comment by ggeorgovassilis** [comment]
Then why doesn't the GIT clone in jenkins work?

**Comment by carlossg** [comment]
It works in the command line, and in a freestyle job, so you may need to configure jenkins or ask in the jenkins mailing list

```
$ docker run --rm -ti jenkins:1.625.3 bash
jenkins@8a3940e31d7e:/$ cd /var/jenkins_home/
jenkins@8a3940e31d7e:~$ git clone https://github.com/jenkinsci/docker.git
Cloning into 'docker'...
remote: Counting objects: 835, done.
remote: Total 835 (delta 0), reused 0 (delta 0), pack-reused 835
Receiving objects: 100% (835/835), 137.50 KiB | 0 bytes/s, done.
Resolving deltas: 100% (422/422), done.
Checking connectivity... done.
```

**Comment by ggeorgovassilis** [comment]
Yes, I probably should. Thanks!
