### ISSUE TITLE
Can't pull on fs layer b2ae0a712b396bf106bd301a41bbff642bd6dfa861596092ac34513b36425241 when pulling image ubuntu:14.04

### ISSUE THREAD

**Issue by willgdjones** [docker-library/docs#449]
Step 1 : FROM ubuntu:14.04
14.04: Pulling from library/ubuntu
fcee8bcfe180: Pulling fs layer
4cdc0cbc1936: Pulling fs layer
d9e545b90db8: Pulling fs layer
c4bea91afef3: Pulling fs layer
Pulling repository docker.io/library/ubuntu
af88597ec24b: Error pulling image (14.04) from docker.io/library/ubuntu, Server error: Status 0 while fetching image layer (b2ae0a712b396bf106bd301a41bbff642bd6dfa861596092ac34513b36425241) 1a41bbff642bd6dfa861596092ac34513b36425241)
b2ae0a712b39: Error pulling dependent layers
Error pulling image (14.04) from docker.io/library/ubuntu, Server error: Status 0 while fetching image layer (b2ae0a712b396bf106bd301a41bbff642bd6dfa861596092ac34513b36425241)

Always fails on b2ae0a712b396bf106bd301a41bbff642bd6dfa861596092ac34513b36425241 :/

**Comment by Moghedrin** [comment]
That's either a firewall issue or some issue with the hub. Try support@docker.com: this isn't a docs issue.
