### ISSUE TITLE
Plans for docker-compose?

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/docs#480]
I saw some stuff around docker-compose here :)
I can see that something is about to happen!

Do you want PRs for ownCloud for instance?
And also, I guess, this could help: https://github.com/docker-library/docs/issues/238

**Comment by yosifkit** [comment]
I don't know of anything new to report on the "compose for official images".  We have a  fairly rudimentary yaml inclusion process; there is one example in [wordpress](https://github.com/docker-library/docs/blob/b7b6b86124682ef11a349b84b27bda24ba53f41f/wordpress/docker-compose.yml) that then becomes part of the ["compose section"](https://github.com/docker-library/docs/tree/b7b6b86124682ef11a349b84b27bda24ba53f41f/wordpress#-via-docker-compose) (with [`content.md`](https://github.com/docker-library/docs/blob/b7b6b86124682ef11a349b84b27bda24ba53f41f/wordpress/content.md#compose) showing how to drop it in).

**Comment by pierreozoux** [comment]
Ok thanks for the aswer.

Do you want PR for others or not?

**Comment by yosifkit** [comment]
I'm not opposed to them :+1:.  It makes sense to show a simple example for the more complex setups.

**Comment by pierreozoux** [comment]
For #238 it needs to ship an nginx conf file I believe.
Like in this setup: https://github.com/indiehosters/ownCloud (official nginx conf from ownCloud doc)

I guess it is not a simple example then.
Would you accept a PR with this compose example?
