### ISSUE TITLE
NGINX environment variables via envsubst break things like $http_host

### ISSUE THREAD

**Issue by pkyeck** [docker-library/docs#496]
When trying to use this as stated in the README

    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

it also replaces stuff like this

    proxy_set_header Host $http_host;

to look like this

    proxy_set_header Host ;

any way to fix this? work around it?

**Comment by pkyeck** [comment]
ok, found a workaround.
one can tell `envsubst` which vars to replace ... so if you know the name of the variables you want to replace you can do it like this:

    command: /bin/bash -c "envsubst '$VAR1 $VAR2' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

and only `$VAR1` and `$VAR2` will be replaced.

**Comment by clintharris** [comment]
For anyone else who Googles there way here with a similar problem, I found that with docker-compose I needed to escape the variables like this:

```
command: /bin/bash -c "envsubst '$$VAR1 $$VAR2' < ...
```

**Comment by lolorama** [comment]
I have problem with docker nginx config setup with envsubst:

`command: '/bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'`

return for me:

`envsubst: error while reading "standard input": Is a directory`

Can someone help to figure out what is wrong?

**Comment by lambarena** [comment]
I am having the same problem with my docker nginx config:

`command: /bin/bash -c "envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"`

Part I want to change:

`proxy_pass  http://${API_PORT_8000_TCP_ADDR}:8000;`

envsubst: error while reading "standard input": Is a directory

Anyone knows how to fix this?

**Comment by teslitsky** [comment]
Worked for me if use `sh` instead of `/bin/bash`.

**Comment by michalgm** [comment]
If you don't want to manage a list of vars to substitute, and only want to substitute anything that has been defined, this seems to do the trick:
`envsubst "`compgen -A variable | tr '\n' ' '`" < /tmp/nginx.conf  > /etc/nginx/conf.d/default.conf`

**Comment by michalgm** [comment]
If you want to only replace variables that have been defined (and not just blindly remove anything else that looks like a variable), this seems to work:
``envsubst "`printf '${%s} \' $(compgen -A variable)`" < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf``

**Comment by charmoniumQ** [comment]
I use Python's [template strings](https://docs.python.org/release/3.6.1/library/string.html#template-strings). I use [this](https://gist.github.com/charmoniumQ/fb489cdfb13836918040144cb63e266b).

**Comment by horrorin** [comment]
In case it helps someone, based on the @michalgm answer, this is the command I use inside my docker-compose.yml file:

```yaml
command: >
    /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\"
    < /etc/nginx/conf.d/mysite.template
    > /etc/nginx/conf.d/default.conf
    && nginx -g 'daemon off;'"
```

**Comment by sschueller** [comment]
> envsubst: error while reading "standard input": Is a directory

If you are having this issue your volume path is most likely wrong. Make sure you if you are using relative paths that you have `./` in front and double check the path exists locally.

**Comment by JavaCS3** [comment]
This work even on`nginx:1-alpine`

Why double "$$" see [doc](https://docs.docker.com/compose/compose-file/#variable-substitution)

```
environment:
      ENV_FOO: ENV_FOO
      ENV_BAR: ENV_BAR
command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```

**Comment by tux255** [comment]
> envsubst: error while reading "standard input": Is a directory
If you use some.template file bash somehow think that it's a diectory
I simply renamed it to some.temp and it worked form me. Do not forget to change config everywhere you need it.

**Comment by tuxflo** [comment]
> This work even on`nginx:1-alpine`
> 
> Why double "$$" see [doc](https://docs.docker.com/compose/compose-file/#variable-substitution)
> 
> ```
> environment:
>       ENV_FOO: ENV_FOO
>       ENV_BAR: ENV_BAR
> command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
> ```

Does anybody know how to use check for empty or unset variables using the awk technique?
("${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment." from [the doc](https://docs.docker.com/compose/compose-file/#variable-substitution))

For example using
```
${PORT:-8080} 
```
doesn't work.

**Comment by JavaCS3** [comment]
> > This work even on`nginx:1-alpine`
> > Why double "$$" see [doc](https://docs.docker.com/compose/compose-file/#variable-substitution)
> > ```
> > environment:
> >       ENV_FOO: ENV_FOO
> >       ENV_BAR: ENV_BAR
> > command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/conf.d/web.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
> > ```
> 
> Does anybody know how to use check for empty or unset variables using the awk technique?
> ("${VARIABLE:-default} evaluates to default if VARIABLE is unset or empty in the environment." from [the doc](https://docs.docker.com/compose/compose-file/#variable-substitution))
> 
> For example using
> 
> ```
> ${PORT:-8080} 
> ```
> 
> doesn't work.

The syntax `${PORT:-8080}` is SHELL(Bash if I remember correct) only. I will prefer you do that in this way. Check [official doc](https://docs.docker.com/compose/compose-file/compose-file-v2/#variable-substitution)

```yaml
environment:
      PORT: ${PORT:-8080}
      ENV_BAR: ENV_BAR
command: sh ...
```

**Comment by tuxflo** [comment]
Just in case anybody else has an issue with that: the substitution works fine if one is setting the version number on the top line of the yaml file:
```
version: '3.3'

services:
  web:
    image: nginx
    environment:
            PORT: ${PORT:-8080}
    ...
    command: sh ...
```

**Comment by milhomem** [comment]
I've put all this in one image https://hub.docker.com/r/milhomem/nginx. This might fix your issue @tuxflo, can you please give a full example of what you are trying to do?

**Comment by tuxflo** [comment]
@milhomem the example is pretty simple: I have a nginx config template with variables and to prevent the replacement of `$http_host` and so on I have to use the `awk` based workaround. I also want to use default variable substitution so that one is able to run 
```
PORT=9090 docker-compose up
```
so set a custom port when staring the container. If the variable is omitted it should use the port that is specified in the `docker-compose.yml` (8080 in the example above). This works just fine if one is using the `version '3'` statement in the first line of the config file.

**Comment by HugoPoi** [comment]
With `nginx:alpine` you do it like this.
Yes it's voodoo shell unreadable
```Dockerfile
FROM nginx:alpine
COPY some.template /etc/nginx/conf.d/default.template
CMD sh -c "envsubst \"`env | awk -F = '{printf \" \\\\$%s\", $1}'`\" < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
```
