### ISSUE TITLE
Starting sentry: adding a secret key might need an `=`?

### ISSUE THREAD

**Issue by NanneHuiges** [docker-library/docs#506]
There are several lines having the `-e SENTRY_SECRET_KEY <secret-key>` in the manual, for example:

    $ docker run -it --rm -e SENTRY_SECRET_KEY <secret-key> --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade

I'm not overly familiar with the option, but I could only get it to work by adding an `=` sign (and quotes because there can be some interpreted characters in there), like so:

        $ docker run -it --rm -e SENTRY_SECRET_KEY='<secret-key>' --link sentry-postgres:postgres --link sentry-redis:redis sentry upgrade

The lines starting with point 4 all need this (if indeed this is an issue, and not just something on my side).

**Comment by yosifkit** [comment]
Yeah, that does need adjusting. Do you want to make a PR to adjust the `content.md`?  Or maybe the maintainer of the image will jump in here (@mattrobenolt).

**Comment by mattrobenolt** [comment]
derp, I'll PR in one second. :)

**Comment by mattrobenolt** [comment]
I think GH is broken, I can't push right now. :(
