### ISSUE TITLE
Why doesn't centos7 include "ip"?

### ISSUE THREAD

**Issue by jamshid** [docker-library/docs#526]
A lot of linux / centos tutorials mention "ip" as a default utility. But I need to `yum install -y iproute` when using docker image centos:centos7. Is this intentional?

**Comment by alvinchevolleaux** [comment]
I think this is a systemd thing and not related to Docker, earlier versions (Centos 6 and below) use the traditional iptables routing mechanisms but Centos 7 uses firewalld.

**Comment by jamshid** [comment]
Ok thanks, what's the proper centos7 / systemd way to check your IP address (like `ip addr show`)?

**Comment by jamshid** [comment]
Ok thanks, what's the proper centos7 / systemd way to check your IP address (like `ip addr show`)?

**Comment by alvinchevolleaux** [comment]
Oh sorry my mistake, I thought you were talking about iptables. If you want to use commands like `ip addr show` you need to do a yum install. The reason is that the Docker boxes are minimal installations on purpose so as not to add any overhead to your environment. In my Dockerfile I need to include commands such as installing sudo or zip, etc.

**Comment by jamshid** [comment]
Okay, but `ip` is a command installed on any minimal centos/rhel install. It's in debian, alpine and busybox images. If `curl` is installed in the centos image (which is nice), seems `ip` should be too. Yes, I know I can build an image on top of centos, but it's often convenient to not have to.

Thanks for replying, feel free to close this. If you happen to know an alternative to get the ip address of the container without having to yum install, please mention.

**Comment by tiangolo** [comment]
For those trying to make this work, it installed with `yum install iproute`. (It wasn't obvious to me what I had to install to have the command `ip`).

**Comment by bcnewlin** [comment]
Sorry for the late add, but I just ran into this today myself. I understand that Docker images should be minimal, but `ip` seems like a strange choice to cut since it is such a basic tool that is almost universally expected to be present.

**Comment by tianon** [comment]
Apologies for not noticing it sooner, but as noted in the image description (https://hub.docker.com/_/centos/, https://github.com/docker-library/docs/blob/1d3fc2d9de64d104d026b932e957eae3dc5df4ab/centos/README.md#issues), this would be more appropriately filed over in the CentOS bug tracker (https://bugs.centos.org/ or https://github.com/CentOS/sig-cloud-instance-images/issues).

This repository is specifically focused on the documentation of the official images, and the CentOS maintainers do not (at least to my knowlegde) monitor issues filed here.  Thanks!

**Comment by tchoutri** [comment]
@tianon Hi! I'm currently struggling because of the absence of `ip` or `ifconfig`. 
How am I supposed to make my internet connection work if I cannot configure my interface to to have an IP / gateway so I can use `yum`… ?? 
The image assumes that a DHCP server is present on the network and gives an IP, and it makes the image unuseable if it's not the case.

**Comment by tianon** [comment]
@tchoutri that sounds like it might be a misunderstanding of how networking in Docker usually works, but I'd recommend either the Docker Forums or the Docker Community Slack as better resources for getting help with issues like that :+1:

**Comment by hervinhio** [comment]
This is resolved by `yum install -y iproute`

**Comment by ruddhani** [comment]
as an update to @hervinhio what I did in my docker centos 7:

```
yum date -y

yum install -y net-tools

yum install -y iproute
```

what I get : 
```
[root@f71060218942 /]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
7: eth0@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever
```

and `#cat /etc/sysconfig/iptables-config` 
showing me the configurations

**Comment by dcaschutz** [comment]
It is 100% not resolved by installing yum. ip and route need to be in the base installation, so as to, say, figure out why I can't reach a yum repo.

Why saslpasswd and all the other crap is in /sbin and not route is an aggravating mystery.

**Comment by jamshid** [comment]
The lack of `ip` (workaround: `yum install -y iproute`), was mentioned in
https://github.com/CentOS/sig-cloud-instance-images/issues/40
but that project owner did not find it compelling. 

So it looks like base centos images will remain ip-less. Crazy.

**Comment by h4nek** [comment]
> For those trying to make this work, it installed with `yum install iproute`. (It wasn't obvious to me what I had to install to have the command `ip`).

That worked. It's `apt install iproute2` on Ubuntu images btw.

**Comment by mike-bailey** [comment]
I got here from googling how to add it and I'm actually against adding it to the base image - a lot of people don't interactively login to their containers (since that'd violate the whole pets vs cattle principle), so none of those people are using `ip` unless it's some bash script or something
