### ISSUE TITLE
Jenkins does not copy empty directorys from /usr/share/jenkins/ref to /var/jenkins_home on start

### ISSUE THREAD

**Issue by ThomasSteinbach** [docker-library/docs#529]
When creating directorys like `RUN mkdir -p /usr/share/jenkins/ref/example/path`, those empty directories would not be copied by the start script to /var/jenkins_home. Thus it becomes very inconvenient to provide empty directories within your Dockerfile.

**Comment by yosifkit** [comment]
Sorry for the long delay; issues dealing with specific image usage should be opened on their own repo.  The maintainers of most repos do not actively watch this general docs repo.

https://github.com/jenkinsci/docker/issues
