### ISSUE TITLE
Volumes dsnt work

### ISSUE THREAD

**Issue by sksourou** [docker-library/docs#538]
hi, 
i try to add my meteor db into the mongo containair. like : 
`docker run --name some-mongo -v /.meteor/local/db:/data/db -d mongo`
but doesnt work. 

```
root@03353fa0c99a:/data/db# ls
WiredTiger  WiredTiger.lock  WiredTiger.turtle  WiredTiger.wt  WiredTigerLAS.wt  _mdb_catalog.wt  collection-0-4603936857331315340.wt  diagnostic.data  index-1-4603936857331315340.wt  journal  mongod.lock  sizeStorer.wt  storage.bson
root@03353fa0c99a:/data/db#
```

ty for ur help and sorry for my english !

**Comment by yosifkit** [comment]
Are you saying that you had a mongo database in `/.meteor/local/db`?  Is it missing a `~/` or `"$PWD"`?  Are you running on Mac or Windows?  With those you can only mount stuff from your host to a container from things inside `/Users/`. Also, Windows and Mac use VirtualBox Shared Folders, which does not work with mongodb.

**Comment by sksourou** [comment]
`pwd = c:/users/me/project/..../db`

So i cant use volumes from windows ?

**Comment by yosifkit** [comment]
Correct "VirtualBox Shared Folders" are not supported by MongoDB.  Related: https://github.com/docker-library/mongo/issues/30#issuecomment-175855264.
