### ISSUE TITLE
Pointing to docs outside Docker Hub

### ISSUE THREAD

**Issue by benbc** [docker-library/docs#549]
Hello. I am one of the maintainers of the official Neo4j image.

We are about to release a new major version of Neo4j which has several significant surface changes. The changes are such that our Docker image documentation will need to be different throughout for the new version compared to older versions.

For example the very simplest example of how to use the image currently includes publishing a single port. For the new release it will be necessary to publish a second port as well.

We would like to change our Docker Hub docs to remove most of the content and replace it with links to documentation on our own docs site. Then we can fork the docs for the two versions and provide links for each version from the Docker Hub page.

Would you be happy to accept a PR to this effect, or can you suggest an alternative approach that you would prefer?

Thanks
-Ben

**Comment by tianon** [comment]
For complex usage, I'm definitely fine with (and +++1) linking to external docs (since they'll likely be more well-maintained and thorough anyhow), but I'd still prefer to have at least basic usage (like which ports are necessary) on the Hub page. :+1:

Does that help? :smile:

**Comment by benbc** [comment]
@tianon It does help. Thanks.
