### ISSUE TITLE
php5-apache: Fatal errors not showing

### ISSUE THREAD

**Issue by danielbjornadal** [docker-library/docs#562]
I cannot enable showing fatal errors at runtime with php5-apache

php.ini

```
error_reporting = E_ALL
display_errors = On
```

.htaccess
`php_flag display_errors 1`

index.php

```
error_reporting(E_ALL);
ini_set('error_reporting', E_ALL);
ini_set('display_errors',1);
```

Website just throws me a 500 error without displaying the actuall error message

**Comment by Moghedrin** [comment]
This doesn't seem like an issue that's in scope for the docker-library/docs. I'm not personally familiar with php, so maybe somebody else will be willing to comment here, but I'm closing this issue.
