### ISSUE TITLE
Registry - Upload purging environment overrides crash registry at startup

### ISSUE THREAD

**Issue by mriddlegsn** [docker-library/docs#580]
Attempting to change the values of the upload purging feature of the docker registry v2.4.0 via environment variables causes the registry to panic and exit on startup with the following message:

panic: uploadpurging config key must contain additional keys

The error is occurring on:
CommitID: 4a915d6efdea23f437cb4144211aaf2faed27774
Line 129
File: registry/handlers/app.go
`purgeConfig, ok = v.(map[interface{}]interface{})`

Setting any upload purging environment variable causes this error to occur such as:
REGISTRY_STORAGE_MAINTENANCE_UPLOADPURGING_AGE: 111168h

When environment variables populate the  "maintenance" map, the key type changes from "interface{}" to "string", which I assume is why the map command is failing.

I added some variable dumping via "spew.Dump()" on those variables and the output is in the attached file called "variable_map_dump.log"

I'm not familiar enough with GO to know how to fix this. I'm hoping this is a trivial fix.

[registry-uploadpurging-bug.zip](https://github.com/docker-library/docs/files/272924/registry-uploadpurging-bug.zip)

**Comment by yosifkit** [comment]
This is probably better reported on https://github.com/docker/distribution/issues. I don't think any of the maintainers follow this repo about the docs on the Docker Hub.
