### ISSUE TITLE
Update README.md - port no longer exposed on 8080 to localhost by default

### ISSUE THREAD

**Issue by f3rgl** [docker-library/docs#587]
When you run: 
`docker run -it --rm tomcat:8.0`
port 8080 is no longer available to localhost (it is only available to other docker containers).  You need to specify -p and explicitly map a port to make to available to localhost.  e.g. 
`docker run -it --rm -p 8888:8080 tomcat:8.0`

**Comment by yosifkit** [comment]
Isn't that what the ["how to use this image"](https://github.com/docker-library/docs/blob/2e2a9bc7e766014ed883bf3f4233adc9922eb1d7/tomcat/README.md#how-to-use-this-image) section says?

With that caveat that if you are on OSX or Windows using `boot2docker`/`docker-machine` then `http://container-ip:8080` would not work, but that is not anything specific to this image and is general to all images.

**Comment by f3rgl** [comment]
Thanks for the response and absolutely, the sample docker run with the -p options is included.  I am on OSX (Docker Beta where the container-ip is localhost) and  using `docker run -it --rm tomcat:8.0`, I am not able to access it on `http://container-ip:8080'. Given this is platform specific, I can close the issue - it just tripped me up when I used it and thought I would highlight it.

**Comment by yosifkit** [comment]
Thanks, hopefully this will help someone in the future on Mac OSX or Windows when they cannot access their tomcat container on port 8080.
