### ISSUE TITLE
docker image available for CentOS-6.5-x86_64-bin-DVD1.iso

### ISSUE THREAD

**Issue by agaddale** [docker-library/docs#610]
Hi,

Is there a docker image available for CentOS-6.5-x86_64-bin-DVD1.iso?

Thanks,
Aarthi G

**Comment by yosifkit** [comment]
Sorry for the long delay; issues dealing with specific image usage should be opened on their own repo. The maintainers of most repos do not actively watch this general docs repo.

https://github.com/CentOS/sig-cloud-instance-images/issues
