### ISSUE TITLE
Can't open perl script "your-daemon-or-script.pl"

### ISSUE THREAD

**Issue by cpngjames** [docker-library/docs#623]
I have tried to follow the flow to install and demo to run the docker image. When it comes to this line: docker run -it --rm --name my-running-app my-perl-app, it returns an error like "Can't open perl script "./your-daemon-or-script.pl": No such file or directory". 

I wonder why Docker can successfully create that file previously but failed to retrieve it afterward.
Step 4 : CMD perl ./your-daemon-or-script.pl
 ---> Running in a9b2f2b94134
 ---> 1fafc9ad9160
Removing intermediate container a9b2f2b94134
Successfully built 1fafc9ad9160

**Comment by yosifkit** [comment]
`CMD` doesn't create a file; it just sets some metadata that is to be run when the container starts.  In you example, `your-daemon-or-script.pl` needs to exist in the file system of the container at the current working directory.
