### ISSUE TITLE
No module named gevent.monkey

### ISSUE THREAD

**Issue by aulsai** [docker-library/docs#695]
Hi All,

Once I ran command
`docker run -d odoo`
The image is odoo:latest

Then odoo's container has started.

Unfortunately it's struggled by this error - as I captured below.

```
2016-09-19 18:21:30,161 9 INFO helpster_id openerp.service.server: Worker WorkerHTTP (9) alive
Traceback (most recent call last):
  File "/usr/bin/openerp-gevent", line 3, in <module>
    import gevent.monkey
ImportError: No module named gevent.monkey
```

Does anyone faced this issue ? Or what do I have to do ?

Thx.

**Comment by yosifkit** [comment]
Sorry for the long delay; issues dealing with specific image usage should be opened on their own repo. The maintainers of most repos do not actively watch this general docs repo.

https://github.com/odoo/docker/issues

**Comment by dek-odoo** [comment]
Late to party but may help someone.

@aulsai You need to install `gevent` like `sudo pip install gevent`.
Optionally if you get error for `psycogreen` install the same like `sudo pip install psycogreen`
