### ISSUE TITLE
MariaDB: MYSQL_RANDOM_ROOT_PASSWORD doesn't generate it

### ISSUE THREAD

**Issue by YahirAlejandro** [docker-library/docs#701]
MYSQL_RANDOM_ROOT_PASSWORD flag doesn't generate a random password.

When running:

`docker run --name test -e MYSQL_RANDOM_ROOT_PASSWORD -p 3308:3306 -v /usr/docker/apps/mariadb/mysql:/var/lib/mysql -d mariadb:5.5
`

stdout is:

>  error: database is uninitialized and password option is not specified  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD

Even when "is set" to yes:
`docker run --name test -e MYSQL_RANDOM_ROOT_PASSWORD=yes -p 3308:3306 -v /usr/docker/apps/mariadb/mysql:/var/lib/mysql -d mariadb:5.5
`

Is some extra juggling with `pwgen` on the command line needed to make this work?

**Comment by yosifkit** [comment]
In the first run you only set the env `MYSQL_RANDOM_ROOT_PASSWORD` to whatever your environment had, which was probably empty, so it failed on that run.  I am not quite sure what would cause the second `docker run` line to fail since I am unable to reproduce it here.  Perhaps your `/usr/docker/apps/mariadb/mysql` is not empty?

This works fine for me:
```console
$ docker run --name test -e MYSQL_RANDOM_ROOT_PASSWORD=yes -p 3308:3306 -d mariadb:5.5
$ docker logs test
Initializing database
<<<< truncated output
160927 23:30:58 [Note] mysqld: ready for connections.
Version: '5.5.52-MariaDB-1~wheezy'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
GENERATED ROOT PASSWORD: haenihohmieheengeijoocahcaiheiha
160927 23:31:00 [Warning] 'proxies_priv' entry '@ root@9de621f98efb' ignored in --skip-name-resolve mode.

/usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*

160927 23:31:00 [Note] mysqld: Normal shutdown

160927 23:31:00 [Note] Event Scheduler: Purging the queue. 0 events
160927 23:31:00  InnoDB: Starting shutdown...
160927 23:31:01  InnoDB: Shutdown completed; log sequence number 1597945
160927 23:31:01 [Note] mysqld: Shutdown complete


MySQL init process done. Ready for start up.

160927 23:31:01 [Note] mysqld (mysqld 5.5.52-MariaDB-1~wheezy) starting as process 1 ...
160927 23:31:01 InnoDB: The InnoDB memory heap is disabled
160927 23:31:01 InnoDB: Mutexes and rw_locks use GCC atomic builtins
160927 23:31:01 InnoDB: Compressed tables use zlib 1.2.7
160927 23:31:01 InnoDB: Using Linux native AIO
160927 23:31:01 InnoDB: Initializing buffer pool, size = 256.0M
160927 23:31:01 InnoDB: Completed initialization of buffer pool
160927 23:31:01 InnoDB: highest supported file format is Barracuda.
160927 23:31:01  InnoDB: Waiting for the background threads to start
```

**Comment by YahirAlejandro** [comment]
@yosifkit  You are right, my directory wasn't empty. It's working fine now with the `MYSQL_RANDOM_ROOT_PASSWORD` set to yes.
Thank you.
