### ISSUE TITLE
POSTGRES_PASSWORD env

### ISSUE THREAD

**Issue by donald122** [docker-library/docs#702]
is it safe to store the password in the POSTGRES_PASSWORD environment. is there a safer way to build the container like using hashed password

**Comment by yosifkit** [comment]
It is possible to create a user with a hased password in postgres: http://stackoverflow.com/a/17431573/433558

> If the presented password string is already in MD5-encrypted format, then it is stored encrypted as-is
> - https://www.postgresql.org/docs/9.6/static/sql-createrole.html

Either way is fine for development, but for production deployment it is best to look into something like [Vault](https://www.vaultproject.io/) or [Kubernetes secrets](http://kubernetes.io/docs/user-guide/secrets/).  There are probably other solutions but it all depends on how you are deploying your services.

**Comment by yosifkit** [comment]
A quick example
```console
$ desiredPassword='test-password'; docker run -d --name postgres -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD="md5$(echo -n "$desiredPassword"'postgres' | md5sum | cut -d' ' -f1)" postgres
```

**Comment by ebrentnelson** [comment]
Any idea why POSTGRES_PASSWORD does seem to work when I start a postgres container? I have cleared out any trace of my original attempt to start the container (without a password), but no matter what I do I am allowed to access postgres with psql without a password. I think I am doing something dumb... I hope.

I do almost the exact same command as the previous post but without a hashed password (this is just for a dev environment at this point). 

I understand this is likely the wrong place for a question like this, but ultimately I want to make sure the docs are still up to date and if there is some sort of gotchya I'd love to get it added to the docs. I tried so many things last night without success.

**Comment by yosifkit** [comment]
@ebrentnelson, how are you accessing postgres?  If you are doing a `docker exec` to test `psql`, then it'll be trusted by the default `pg_hba.conf` since it is connecting via localhost or the unix socket.  Here is the `pg_hba.conf` that is used when a password is supplied:

```console
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
# Allow replication connections from localhost, by a user with the
# replication privilege.
#local   replication     postgres                                trust
#host    replication     postgres        127.0.0.1/32            trust
#host    replication     postgres        ::1/128                 trust

host all all all md5
```

Also, it looks like the original issue was fixed, so I'll close the issue.  If either of you still are having issues or  questions please let us know.  It might be better to file postgres specific questions on https://github.com/docker-library/postgres, since this repo is more specifically for issues in the documentation that appears on the Docker Hub.

**Comment by ebrentnelson** [comment]
This is exactly correct. Thanks yosifkit. I tried connecting from another machine and it prompted me for password as expected. 

I will create a PR with a note in the docs (surely I'm not the only dummy out there....but maybe I am).

**Comment by yosifkit** [comment]
Thanks! (also note to edit `content.md` and not `README.md` in the postgres folder; I'm working to make that more clear in the coming week)
