### ISSUE TITLE
Service Advertised with internal Docker ip

### ISSUE THREAD

**Issue by Cibico99** [docker-library/docs#704]
I am having an issue where my service is being advertised with the internal Docker ip. (172.17.0.2)
I need the consul agent to use its advertised IP, for the service location, instead of the IP that the service contacted it on.
Is there a way to do this?

**Comment by yosifkit** [comment]
You may want to open your issue on the [docker-consul repo](https://github.com/hashicorp/docker-consul/issues); many of the image maintainers do not actively watch this documentation repo.

**Comment by Cibico99** [comment]
Had to use Registrator.... only solution
