### ISSUE TITLE
Docker | Gazebo gzclient GUI not displaying on OS X El Capitan

### ISSUE THREAD

**Issue by ceobillionaire** [docker-library/docs#710]
On _OS X El Capitan (version 10.11.6)_, when running:

```
$ export GAZEBO_MASTER_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' gazebo)
$ export GAZEBO_MASTER_URI=$GAZEBO_MASTER_IP:11345
$ gzclient --verbose
```

I get:

`[Msg] Waiting for master.`

Then, nothing happens (I have Gazebo version 7.3.1 installed locally).

**Comment by yosifkit** [comment]
Sorry for the delay; issues dealing with specific image usage should be opened on their own repo. The maintainers of most repos do not actively watch this general docs repo.

https://github.com/osrf/docker_images/issues
