### ISSUE TITLE
Question: How to upgrade notary client to work for signer/server 0.3.0?

### ISSUE THREAD

**Issue by LenutaToderean** [docker-library/docs#724]
Hi! 
I installed notary using:
>sudo apt-get update
>sudo apt-get install notary

I need for a latest version of notary client in order to add delegates. I am trying to update my notary client  and I didn't manage to do this. Any small information will be very usefully. Thank you!

**Comment by yosifkit** [comment]
This repo deals with the documentation as it pertains to all official images.  Most of the maintainers of the images do not actively watch here.  If you are having issues with the notary images, then you may want to open an issue on their repo: https://github.com/docker/notary-official-images/issues.

**Comment by LenutaToderean** [comment]
@yosifkit ..ok ... thank you!

**Comment by LenutaToderean** [comment]
![image](https://cloud.githubusercontent.com/assets/19945972/19427070/12088f80-944a-11e6-8275-93abb0b7e87e.png)

I am asking because this is the official documentation and I have no idea what to do. Thank you!

**Comment by LenutaToderean** [comment]
The documentation in the official site is not available (see below). Thank you!

![image](https://cloud.githubusercontent.com/assets/19945972/19427095/4dcc7c52-944a-11e6-8162-42e4ba410d45.png)
