### ISSUE TITLE
Question about PHP extensions in Debian packages

### ISSUE THREAD

**Issue by mstenta** [docker-library/docs#733]
I have a Dockerfile that inherits from these images. I would like to install the GEOS extension (), which is available in Debian via the `php5-geos` package.

I have installed that package via `apt-get`, but it seems that PHP cannot find the library. Upon reading the documentation for these images, it sounds like I might have to build from source?

Specifically: https://github.com/docker-library/docs/tree/master/php#other-extensions

Is it possible to use the official Debian `php5-geos` package? Or do I need to build the library from source?

If I search for the geos.so library file, I find it is installed in `/usr/lib/php5/20131226/geos.so`, but it appears that PHP in this image is looking for it in `/usr/local/lib/php/extensions/no-debug-non-zts-20131226`.

Any advice or info would be appreciated!

**Comment by Moghedrin** [comment]
This is pretty well documented in the [existing documentation](https://hub.docker.com/r/_/php/), you've got to build the library from source, though there are helpful tools in the image to facilitate this. :)
