### ISSUE TITLE
Tag latest not found in repository docker.io/library/<package>

### ISSUE THREAD

**Issue by dieuit07** [docker-library/docs#740]
Hi everyone, when build a dockerfile. 

```
FROM ruby:latest
MAINTAINER ...
```

I receive some info:

```
Pulling repository docker.io/library/ruby
bfe1e909440a: Download complete 
33a372e3ad95: Download complete 
1230b07f5c40: Download complete 
0ebd84a329dd: Download complete 
...
Pulling repository docker.io/library/ruby
Tag latest not found in repository docker.io/library/ruby
```

I try with run in console 'docker pull ruby' , it through the same error.

Is it a problem of docker server?

**Comment by Moghedrin** [comment]
Seems like this was an issue with docker's server on that particular day, rather than an issue with the documentation. ;D
