### ISSUE TITLE
PHP PECL memcached example from docs does not work

### ISSUE THREAD

**Issue by mariusgrigaitis** [docker-library/docs#764]
https://github.com/docker-library/docs/tree/master/php#php-core-extensions

```
FROM php:7.0-fpm
RUN apt-get update && apt-get install -y libmemcached-dev \
    && pecl install memcached \
    && docker-php-ext-enable memcached
```

Output: https://gist.github.com/mariusgrigaitis/5bc04c0bab82aed2b64502edc0438570

**Comment by mariusgrigaitis** [comment]
Related: https://github.com/docker-library/php/issues/317

**Comment by tianon** [comment]
Ah, the stable version of the `memcached` extension doesn't support PHP 7 yet (https://pecl.php.net/package/memcached/2.2.0):

> PHP Version: PHP version 6.0.0 or older
> PHP Version: PHP 5.2.0 or newer

It would appear upstream there has a branch for developing PHP 7 support: https://github.com/php-memcached-dev/php-memcached/tree/php7

I'll make a PR to update that example to both pin to a specific version of the memcached extension (so we don't get more nasty surprises -- generally good best practice anyhow) and to no longer use PHP 7.0 there for now. :+1:

**Comment by tianon** [comment]
https://github.com/docker-library/docs/pull/767 :metal:

**Comment by mariusgrigaitis** [comment]
Maybe proper solution would be to use some other pecl module other than memcached.

We could have an example using php7.0 then

**Comment by yosifkit** [comment]
I am all for having another example.  Do you have one in mind?

**Comment by mariusgrigaitis** [comment]
`xdebug` or `redis` seems to work fine for 7.* branches.
