### ISSUE TITLE
Document Redmine environment variables

### ISSUE THREAD

**Issue by imaia** [docker-library/docs#769]
It would be nice to have all out-of-the-box environment variables described in the image docs.

**Comment by yosifkit** [comment]
To which images are you referring?  We try to make sure to document any added environment variables, but ofttimes it does get left out.

**Comment by imaia** [comment]
redmine image

**Comment by typia** [comment]
+1
I'd like to know redmine environment varibles to be able to customize db, user and password instead of having to provide root db password when using external database

**Comment by tianon** [comment]
Yeah, we could use some documentation on these.  For reference, here's the bits of code that determine which we support depending on database type:

For MySQL: https://github.com/docker-library/redmine/blob/c137cd0e39758f56be851cbd56273cd486590149/docker-entrypoint.sh#L40-L45

For PostgreSQL: https://github.com/docker-library/redmine/blob/c137cd0e39758f56be851cbd56273cd486590149/docker-entrypoint.sh#L48-L53

For SQLite: https://github.com/docker-library/redmine/blob/c137cd0e39758f56be851cbd56273cd486590149/docker-entrypoint.sh#L63-L67

**Comment by wglambert** [comment]
Resolved with https://github.com/docker-library/docs/pull/906
