### ISSUE TITLE
update mongodb docs, --link is deprecated

### ISSUE THREAD

**Issue by AlJohri** [docker-library/docs#786]

**Comment by tianon** [comment]
As far as I'm aware, `--link` is _discouraged_, but not officially deprecated yet (and is the simplest form of connecting two containers to one another).

**Comment by dhoinka** [comment]
According to the docs it is.

> Warning: The --link flag is a deprecated legacy feature of Docker.
[docker docs](https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/)

**Comment by tianon** [comment]
See https://github.com/docker-library/docs/pull/1063 for another discussion of this same topic.

Essentially, `--link` is still actively supported, and does not print a deprecation warning on use.  There are no near-term plans that I'm aware of to remove the feature it provides.

We use `--link` in the documentation as a very short from of `docker network` which doesn't require explicit network creation or cleanup, and the astute Docker reader ought to be able to make the conversion to networks.  I'd be open to adding a short blurb to each (first-per-image-description) usage of `--link` to link to some good `docker network` documentation, but we'll need to come up with good wording for it before we copy-paste it to every description (which in itself feels like we're trending down the wrong path).

It definitely feels completely backwards to pollute every image description with a long-form example that sets up custom networks just for the purposes of showing how to connect a database to an application container.

**Comment by tianon** [comment]
See also https://github.com/docker-library/faq#--link-is-deprecated. 👍
