### ISSUE TITLE
Need recommended `.dockerignore` for onbuilds

### ISSUE THREAD

**Issue by yosifkit** [docker-library/docs#79]
Node, Ruby, Rails

**Comment by tianon** [comment]
Updated list:
```console
$ bashbrew list --all | grep ':onbuild$'
django:onbuild
golang:onbuild
iojs:onbuild
maven:onbuild
mono:onbuild
node:onbuild
pypy:onbuild
python:onbuild
rails:onbuild
ruby:onbuild
```

**Comment by tianon** [comment]
Further updated list........
```console
$ bashbrew list --all | grep ':onbuild$'
clojure:onbuild
django:onbuild
erlang:onbuild
golang:onbuild
iojs:onbuild
maven:onbuild
mono:onbuild
node:onbuild
pypy:onbuild
python:onbuild
rails:onbuild
ruby:onbuild
sentry:onbuild
```

It might be enough to add something generic about this to [`.template-helpers/variant-onbuild.md`](https://github.com/docker-library/docs/blob/5d45830797c837126d7802b0fab114075dac11b6/.template-helpers/variant-onbuild.md) (which already discourages extended use of `:onbuild` tags).

**Comment by yosifkit** [comment]
Onbuild images are being deprecated: https://github.com/docker-library/official-images/issues/2076
