### ISSUE TITLE
Unknown instruction: ADDGROUP in docker new beta version

### ISSUE THREAD

**Issue by number9code** [docker-library/docs#792]
<img width="415" alt="screen shot 2017-01-06 at 1 50 15 pm" src="https://cloud.githubusercontent.com/assets/3821967/21708866/6fa092d4-d417-11e6-9e8d-b456261cd1a5.png">

**Comment by tianon** [comment]
This looks like something wrong in your `Dockerfile` -- can you provide the full `Dockerfile` you're attempting to build, and the output of both `docker version` and `docker info` on the system where you're compiling it?
