### ISSUE TITLE
docker run - Exposing Consul's DNS Server on Port 53 - failure on Ubuntu

### ISSUE THREAD

**Issue by vramakrishnan** [docker-library/docs#812]
I am running the command suggested (for exposing consul dns server on 53) on Ubuntu VM and ran into docker run and container creation failure.  There are no relevant daemon logs for this, suggesting there might be issue in command parsing for CONSUL_ALLOW_PRIVILEGED_PORTS.

Appreciate any help in this regard.

**es_consul@consul-vm-1:/$ uname -a**
Linux consul-vm-1 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**es_consul@consul-vm-1:/$ docker version**
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**es_consul@consul-vm-1:/$ docker run -d --net=host -e 'CONSUL_ALLOW_PRIVILEGED_PORTS=' consul -dns-port=53 -recursor=8.8.8.8**
f364f735afdadf752c679e8c9d96c91594f67f6ff88f3e14e9699231de877474

**es_consul@consul-vm-1:/$ docker ps -a**
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                    PORTS               NAMES
f364f735afda        consul              "docker-entrypoint..."   2 seconds ago       Exited (1) 1 second ago                       gracious_poincare

**es_consul@consul-vm-1:/$ docker logs f3**
error: exec failed: text file busy

**es_consul@consul-vm-1:/$ journalctl -u docker.service | grep f364f735afda**
Jan 26 02:21:31 consul-vm-1 dockerd[18550]: time="2017-01-26T02:21:31.535104422Z" level=error msg="containerd: deleting container" error="exit status 1: \"container f364f735afdadf752c679e8c9d96c91594f67f6ff88f3e14e9699231de877474 does not exist\\none or more of the container deletions failed\\n\""

**Comment by yosifkit** [comment]
I think this would be better reported in https://github.com/hashicorp/docker-consul/issues.  Many official-image maintainers do not actively watch this repo.

**Comment by vramakrishnan** [comment]
The issue is now moved to hashicorp project. Closing this one.
