### ISSUE TITLE
Can't add first user admin

### ISSUE THREAD

**Issue by Waog** [docker-library/docs#815]
When following your readme (starting a DB with the `--auth` flag and adding an admin via `db.createUser`) to configure authorization, I get the following error:

```
2017-01-28T01:31:25.922+0000 E QUERY    [main] Error: couldn't add user: not authorized on admin to execute command { createUser: "admin", pwd: "xxx", roles: [ { role: "userAdminAnyDatabase", db: "admin" } ], digestPassword: false, writeConcern: { w: "majority", wtimeout: 300000.0 } } :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.createUser@src/mongo/shell/db.js:1290:15
@(shell):1:1
```

In constrast to your docs I don't use the `docker exec -it some-mongo mongo admin` command to add the admin, but connect from another containers mongo client.

**Comment by yosifkit** [comment]
You have to use `docker exec` to create the initial user; MongoDB will only accept connections via localhost to create the initial user.  It is possible to use another container but it would need to be in the same network namespace (ie, `--network=some-mongo`) so that it can connect via localhost.
