### ISSUE TITLE
Hello world docs outdated

### ISSUE THREAD

**Issue by vitorreis** [docker-library/docs#836]
On https://hub.docker.com/_/hello-world/

We can see this instruction

>See hello.asm in https://github.com/docker-library/hello-world for the source code of the hello binary included in this image.

but this repo does not have `hello.asm` anymore. The docs needs to be updated

**Comment by yosifkit** [comment]
Thanks for the note! :heart:

Yeah, we had to change it so we could build on more architectures (https://github.com/docker-library/hello-world/pull/17).

**Comment by vitorreis** [comment]
I see, I will open a pr to fix it  :) thanks for the context.
