### ISSUE TITLE
[!!!!!!] Failed to mount API filesystems, freezing.

### ISSUE THREAD

**Issue by msavdert** [docker-library/docs#846]
Hello,

I am trying to Systemd integration by following the instructions in the centos Readme Document.

I have already created local /c7-systemd as described in the documentation.

my Dockerfile contain

FROM local/c7-systemd
RUN yum -y install httpd; yum clean all; systemctl enable httpd.service
EXPOSE 80
CMD ["/usr/sbin/init"]

Build this image:

$ docker build --rm -t local/c7-systemd-httpd .

**Not:** I think you have forgotten to put a dot here at the end of the code.

$ docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/c7-systemd-httpd
[!!!!!!] Failed to mount API filesystems, freezing.

Can someone help me with this?

Thank you,
Melih

**Comment by yosifkit** [comment]
This would probably be better to open on https://github.com/CentOS/sig-cloud-instance-images/issues; most of the official image maintainers don't watch this repository too closely.

**Comment by Moghedrin** [comment]
Seems like there's a solution listed over in the repo that yosifkit pointed to: https://github.com/CentOS/sig-cloud-instance-images/issues/54
