### ISSUE TITLE
Run update.sh fail

### ISSUE THREAD

**Issue by yuniers** [docker-library/docs#853]
On my computer when I try `./update.sh centos` an error is triggered
```sh
sosa@DGP-DT-211:/home/sosa/docs$ ./update.sh centos
  TAGS => generate-dockerfile-links-partial.sh
error: failed executing template
template: .template-helpers/generate-dockerfile-links-partial.tmpl:17:15: executing ".template-helpers/generate-dockerfile-links-partial.tmpl" at <$.DockerFrom>: error calling DockerFrom: exit status 128
```

However, when I try `./update.sh alpine` all is Ok.

[Centos](https://raw.githubusercontent.com/docker-library/official-images/master/library/centos) and [Alpine](https://raw.githubusercontent.com/docker-library/official-images/master/library/alpine) files have a very different format.

**Comment by yosifkit** [comment]
It is not the file format; bashbrew can handle both.  Most likely centos has updated their repo with new commits (via force push) and so the old references are now lost (still accessible via github, but `git` can't download them).
