### ISSUE TITLE
older tags not working

### ISSUE THREAD

**Issue by MielHostens** [docker-library/docs#856]
Can somebody else verify but i guess older tags don't work

for me docker.elastic.co/elasticsearch/elasticsearch:2.4 or docker.elastic.co/elasticsearch/elasticsearch:2.4.4 does not work when do a docker pull

**Comment by Moghedrin** [comment]
I definitely can't pull either 2.4 or 2.4.4, so it's not just you. That being said, we don't maintain the elasticsearch images, so if you want an official docker image of an older version, you'll have to take that up with [upstream](https://github.com/elastic/elasticsearch-docker).
