### ISSUE TITLE
Memory watermark info

### ISSUE THREAD

**Issue by AnatolyRugalev** [docker-library/docs#878]
We need to describe behavior of `RABBITMQ_VM_MEMORY_HIGH_WATERMARK` variable, which was introduced in recent image tag.

https://github.com/docker-library/rabbitmq/blob/master/3.6/debian/docker-entrypoint.sh#L269

**Comment by tianon** [comment]
:metal: (https://github.com/docker-library/docs/blob/be9b754da9ed1f6ee04b46576e39a1d96d310435/rabbitmq/content.md#memory-limits)

Added in https://github.com/docker-library/docs/pull/879. :+1:
