### ISSUE TITLE
README.md has typo and is outdated (missing --privileged=true)

### ISSUE THREAD

**Issue by attila123** [docker-library/docs#892]
I arrived to https://github.com/docker-library/docs/tree/master/centos#systemd-integration from http://stackoverflow.com/questions/28495341/start-a-service-in-docker-container-failed-with-error-failed-to-get-d-bus-conne

Following the steps I found a typo in README.md: ' .' (dot) is missing at the end of the following line:
```console
$ docker build --rm -t local/c7-systemd-httpd
```
So it should be:
```console
$ docker build --rm -t local/c7-systemd-httpd .
```

I am new to docker, but I could figure it out from the previous similar line.

Also, when I ran:
```console
docker run -ti -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/c7-systemd-httpd
```
I got:
```console
[!!!!!!] Failed to mount API filesystems, freezing.
```

I needed to kill this docker process and restart the docker service (because it kept listening on port 80).
I found the solution at http://stackoverflow.com/questions/36617368/docker-centos-7-with-systemctl-failed-to-mount-tmpfs-cgroup from the accepted command: --privileged=true was missing from the docker command. With that, I got it working:

```console
$ docker run -ti --privileged=true -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 local/c7-systemd-httpd
systemd 219 running in system mode. (+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 -SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
Detected virtualization docker.
Detected architecture x86-64.

Welcome to CentOS Linux 7 (Core)!

Set hostname to <93a33222fe2f>.
Initializing machine ID from random generator.
Failed to install release agent, ignoring: File exists
[  OK  ] Reached target Paths.
[  OK  ] Reached target Local File Systems.
[  OK  ] Reached target Swap.
[  OK  ] Created slice Root Slice.
[  OK  ] Listening on Delayed Shutdown Socket.
[  OK  ] Listening on Journal Socket.
[  OK  ] Created slice System Slice.
         Starting Create Volatile Files and Directories...
[  OK  ] Reached target Slices.
         Starting Journal Service...
[  OK  ] Started Create Volatile Files and Directories.
[ INFO ] Update UTMP about System Boot/Shutdown is not active.
[DEPEND] Dependency failed for Update UTMP about System Runlevel Changes.
Job systemd-update-utmp-runlevel.service/start failed with result 'dependency'.
[  OK  ] Started Journal Service.
[  OK  ] Reached target System Initialization.
[  OK  ] Reached target Timers.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Reached target Basic System.
         Starting The Apache HTTP Server...
         Starting Cleanup of Temporary Directories...
[  OK  ] Started Cleanup of Temporary Directories.
[  OK  ] Started The Apache HTTP Server.
[  OK  ] Reached target Multi-User System.
```

I am on Linux Mint 18.1, which is based on Ubuntu 16.04.

```console
$ uname -a
Linux hp-g1 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ docker -v
Docker version 17.04.0-ce, build 4845c56
```

Even though it works with --privileged=true it is too strong permission.

Please update README.md accordingly!

**Comment by yosifkit** [comment]
I made a quick commit for the missing build context. :smile:

As for the `--privileged=true` for systemd, there is a blog post on [redhat](https://developers.redhat.com/blog/2016/09/13/running-systemd-in-a-non-privileged-container/) that should get you a systemd container without needing to give it full access, but it looks like he assumes you are running systemd on the host.  The systemd in the container will have all access to the systemd cgroups of anything running on the host.
