### ISSUE TITLE
Adding "Try in PWD" buttons

### ISSUE THREAD

**Issue by marcosnils** [docker-library/docs#912]
I was thinking about adding "Try in PWD" buttons (https://medium.com/@marcosnils/showcasing-your-applications-with-docker-in-a-single-click-9e9fa2908c51) to some of the official images so it's easier to showcase them. 

Here's an example button for the redis image:

[![Try in PWD](https://cdn.rawgit.com/play-with-docker/stacks/cff22438/assets/images/button.png)](http://play-with-docker.com?stack=/redis/latest)

Is this something that I need to talk with the image owners?. How would you recommend to proceed?

**Comment by yosifkit** [comment]
@tianon and I maintain many of the official images and we'd love to have a simple button for users to try a stack.yml file here in the docs similar to our current docker-compose files (like [wordpress](https://github.com/docker-library/docs/blob/a6d6ff08d02e0f9382d433d0cb06fb71386ba1da/wordpress/docker-compose.yml)). But it looks like play-with-docker is currently limited to just stack files from `play-with-docker/stacks` (https://github.com/play-with-docker/play-with-docker/pull/138, https://github.com/play-with-docker/play-with-docker/pull/142).  Are you planning to allow users to provide a stack file on the button?  This would be a great demoing tool to stick on many github projects.

As for official images that are maintained by upstream or community members, they can be as involved as they would like in any stack files created here (or opt-out from a stack file if they desire).

**Comment by marcosnils** [comment]
hey @yosifkit thx for the quick response. The "Try in PWD" actually supports to specify any stackfile that's available on the web. In the `stack` parameter you can either add a relative path of a stack in the `stacks` repo or a URL. The syntax for that is `[![Try in PWD](https://cdn.rawgit.com/play-with-docker/stacks/cff22438/assets/images/button.png)](http://play-with-docker.com?stack=https://<my_stack_url>)`.

I didn't know that you already had sample stacks in this repo for the official images. The reason why we created our own repo is mainly for the Chrome extension and because there wasn't a place were we could get curated stack files. Additionally we wanted to have everything in one place (button + stacks) so users know how to use it.

So, now that you know that the button support loading stacks from anywhere, shall we start opening PR's to add buttons?. Do we need to bring the stacks from the stacks repo here?
