### ISSUE TITLE
Rebuild sonar docker image

### ISSUE THREAD

**Issue by javixeneize** [docker-library/docs#922]
Hi

I would like to create a docker image with some specific plugins on it. 

I know that it can be added later to the extensions volume, but i would like to have the image with those plugins already contained there

How should i do that? Should i modify the dockerfile to include the reference to those plugins?

Thanks

**Comment by tianon** [comment]
This would probably be better filed over on https://github.com/SonarSource/docker-sonarqube -- the maintainers of the SonarQube image aren't likely to see issues filed on the general official-images documentation repository. :sweat_smile:
