### ISSUE TITLE
Couchbase example docs doesn't show latest available tag

### ISSUE THREAD

**Issue by tleyden** [docker-library/docs#935]
In [this Couchbase sample doc](https://docs.docker.com/samples/couchbase/), under the **Supported tags and respective Dockerfile links** section it shows the latest tag as `4.6.1`, but the latest tag is actually `4.6.2`, which is correctly reflected in [docker-library/docs](https://github.com/docker-library/docs/tree/master/couchbase/)

Is there something we need to do on our end to get the sample doc updated?  From the looks of it, that section is auto-generated.

**Comment by tianon** [comment]
I had no idea that section even existed (or where it comes from or why it was added)! :sweat_smile:

cc @thaJeztah perhaps you can help shed some light on what this is, why it exists, or why it isn't being updated properly?

**Comment by thaJeztah** [comment]
Oh, I think this was done by @johndmulhausen - I don't know how frequent (and when) these are updated

**Comment by johndmulhausen** [comment]
Unfortunately I'm just not sure how that's updated. You would think automatically based on metadata?

**Comment by tianon** [comment]
Looks like https://github.com/docker/docker.github.io/pull/3063 is the PR which added it, and it appears to be using a Git submodule to link to/embed the official-images docs repo?

**Comment by salazar** [comment]
Noticed this as well with Kong. Looks like it's updated by [this script](https://github.com/docker-library/docs#template-helpersgenerate-dockerfile-links-partialsh).

**Comment by tianon** [comment]
Is this fixed?  Regardless it's not something we can fix here -- somewhere else is consuming and re-publishing these repo contents there, so the best we can do is prod the maintainers of that other bit and have them update their references.

Not sure if it was there when this was filed, but there does now appear to be a warning at the top of the page noting where the "canonical" source of these docs are (linking to the Docker Store, which does sometimes have a delay in getting the updated image descriptions from the Docker Hub in my experience).
