### ISSUE TITLE
SED Error

### ISSUE THREAD

**Issue by JaniDJ** [docker-library/docs#949]
Hey Folks!

I started a new Container with xWiki:

`docker run --network="****" --name xWiki -p 8080:8080 -v ****:/usr/local/xwiki -e DB_USER=**** -e "DB_PASSWORD=****" -e DB_DATABASE=**** -e DB_HOST=**** xwiki:mysql-tomcat`

The Container dies instant and I'm getting this 

> sed: -e expression #1, char 38: unknown option to `s'

Thanks for any help!

**Comment by tianon** [comment]
I think you're going to want to file this under [the XWiki Docker JIRA project](http://jira.xwiki.org/browse/XDOCKER) so that the maintainers of the `xwiki` image see it, since they don't track this repo for their issues (this is the repository for the image documentation only). :+1:

**Comment by JaniDJ** [comment]
Oh sh*t! Sorry I was in the wrong thread. Excuse me!!!
