### ISSUE TITLE
Docker Cassandra 3.10

### ISSUE THREAD

**Issue by prabha101** [docker-library/docs#959]
Hi, I've been using Docker Cassandra Container Image 3.10 for the last 3 months. I see that this Repository has completely been taken down and a there's a new 3.11 update. Can you at least put the 3.10 Repository back for folks who've been working out of this version? Thank you!
Prabha

**Comment by tianon** [comment]
This is only the repository for the documentation -- the Cassandra Dockerization itself is over in https://github.com/docker-library/cassandra.

If you look at https://cassandra.apache.org/download/, you'll see that Cassandra 3.10 is no longer supported (see also http://www.planetcassandra.org/blog/cassandra-2-2-3-0-and-beyond/ for more information).

Additionally, see https://hub.docker.com/r/library/cassandra/tags/ -- `cassandra:3.10` still exists and is available to pull, it is simply unsupported and will receive no further updates.
