### ISSUE TITLE
Clarification between Docker-Cassandra 3.10 and Apache Cassandra 3.10

### ISSUE THREAD

**Issue by prabha101** [docker-library/docs#987]
Hi can you please let me know if docker Cassandra Container Image 3.10 is the same software stack as Apache Cassandra 3.10?
https://hub.docker.com/r/library/cassandra/tags/ -- cassandra:3.10

vs.

https://github.com/apache/cassandra/tree/cassandra-3.10

vs.

http://archive.apache.org/dist/cassandra/3.10/apache-cassandra-3.10-bin.tar.gz

Thanks,
Prabha

**Comment by tianon** [comment]
If you click one of the links at https://hub.docker.com/_/cassandra/ (such as 3.11), you'll get the exact `Dockerfile` used to build that tag.  In the case of 3.11, that's currently https://github.com/docker-library/cassandra/blob/f6f09faf3e50e648ec11a9676a29dd1130604c2d/3.11/Dockerfile, which pulls Cassandra directly from the upstream Apache deb repo at http://www.apache.org/dist/cassandra/debian (and 3.10 would've been the same).
