### ISSUE TITLE
Clarify issues that SELinux may cause

### ISSUE THREAD

**Issue by davidmichaelkarr** [docker-library/docs#991]
In a few places in the README, it states the following:

```Note that users on host systems with SELinux enabled may see issues with this.```

It would really be nice for users who don't work with this every day to see a clarification of what "issues" means.  For instance, simply saying something like:

```Note that users on host systems with SELinux enabled may see problems like "chown: changing ownership of '/var/lib/mysql/': Permission denied".```

This is what happened to me, and if it had read more like this I might have recognized the symptom as being caused by this, instead of having to be lead by the hand to this issue.

**Comment by tianon** [comment]
Honestly, I'd prefer to find a good doc from Docker upstream about SELinux
specific issues and then simply have a blurb something like "Getting
'Permission denied' errors and using SELinux?  See XYZ upstream
documentation."

**Comment by tianon** [comment]
Even linking to something like
https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
would probably be sufficient, since it talks about ":z" and ":Z" as well.

**Comment by tianon** [comment]
Is that old blog post still the best reference for this that we could link to? :disappointed:

**Comment by tianon** [comment]
I think https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label is the only "official" reference we could link to, although http://jaormx.github.io/2018/selinux-and-docker-notes/ is a pretty decent (newer) article on the subject.

I'm really a bit tempted to simply remove the SELinux specific notes from our instructions entirely -- those really aren't an image-specific concern, and apply to usage of Docker on SELinux much more generally, so it feels excessive for us to explicitly discuss SELinux in our image documentation.
